/************************************************************************************
 * Filename: lookup_tables.c
 *
 * Notice:
 *           THIS FILE AUTOMATICALLY GENERATED BY SPREADSHEET
 *                   ModbusMap.xlsm. 
 *           MANUAL UPDATES TO THIS FILE WILL BE LOST.
 *
 *
***************************************************************************************
 *
 *
 *=====================================================================================
 * Description:
 *   C file for the Modbus registers and coil lookup tables. These tables map
 *   the registers/coils from Modbus to the appropriate location (I/O Processor or
 *   Sensor Processor). It also defines attributes such as type and protection.
 *
 * External Interface Functions:
 *   N/A
 *
 * Internal Functions:
 *   N/A
 * 
***************************************************************************************/
#include <stdint.h>
#include "lookup_tables.h"
//
#define OFFSET(field) ( (uint16_t)offsetof(tDeviceBasicParams, field) )
//
// This is main storage for device parameters packed by 1 byte
#pragma pack(push, 1)
tDeviceBasicParams g_deviceDataStorage = {0};
#pragma pack(pop)
  
extern uint8_t mbRegRwCheckFunc(void* param, void* buffer);


// Register Map Definition
const tLookupRegisters g_stLookupRegisters[] =
{
    // {Par Offset, NV Offset, Check Func, Parameter Offset, Data Type, Data Size, Work Mode Access | Service Mode Access | Write Protect}
    // Parameter: Data channel 0 : DataChan0
    {0, 0,  OFFSET(DataChan0), "DataChan0", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 1 : DataChan1
    {2, 0,  OFFSET(DataChan1), "DataChan1", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 2 : DataChan2
    {4, 0,  OFFSET(DataChan2), "DataChan2", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 3 : DataChan3
    {6, 0,  OFFSET(DataChan3), "DataChan3", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 4 : DataChan4
    {8, 0,  OFFSET(DataChan4), "DataChan4", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 5 : DataChan5
    {10, 0,  OFFSET(DataChan5), "DataChan5", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 6 : DataChan6
    {12, 0,  OFFSET(DataChan6), "DataChan6", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data channel 7 : DataChan7
    {14, 0,  OFFSET(DataChan7), "DataChan7", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Protocol version  : protocolVersion
    {16, 0,  OFFSET(protocolVersion), "protocolVersion", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Hardware version  : hardwareVersion
    {18, 4,  OFFSET(hardwareVersion), "hardwareVersion", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Software Version : softwareVersion
    {20, 8,  OFFSET(softwareVersion), "softwareVersion", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Serial number  : serialNumber
    {22, 12,  OFFSET(serialNumber), "serialNumber", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Device Type : deviceType
    {24, 16,  OFFSET(deviceType), "deviceType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Factory date  : factoryDate
    {25, 18,  OFFSET(factoryDate), "factoryDate", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Software CRC32  : softwareCrc32
    {27, 22,  OFFSET(softwareCrc32), "softwareCrc32", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Unique ID  : uniqueId
    {29, 26,  OFFSET(uniqueId), "uniqueId", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Mode  : deviceMode
    {35, 532,  OFFSET(deviceMode), "deviceMode", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Modbus Baudrate : modbusBaud
    {36, 26,  OFFSET(modbusBaud), "modbusBaud", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Modbus parity  : modbusParity
    {37, 28,  OFFSET(modbusParity), "modbusParity", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Modbus stopbit  : mbStopBits
    {38, 30,  OFFSET(mbStopBits), "mbStopBits", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Data order : dataOrder
    {39, 32,  OFFSET(dataOrder), "dataOrder", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Modbus comm count  : mbCommCount
    {40, 34,  OFFSET(mbCommCount), "mbCommCount", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Modbus comm error  : mbCommError
    {42, 34,  OFFSET(mbCommError), "mbCommError", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Access type  : accessType
    {44, 34,  OFFSET(accessType), "accessType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Errors : devErrors
    {45, 34,  OFFSET(devErrors), "devErrors", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Up time  : uptime
    {46, 34,  OFFSET(uptime), "uptime", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: configDeviceType : configDeviceType
    {48, 34, OFFSET(configDeviceType), "configDeviceType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    //
    {500, 34,  OFFSET(hashRoot), "hashRoot", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_W},
    // Parameter: Update Software : updateSoftware
    {501, 34, OFFSET(updateSoftware), "updateSoftware", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_W},
    // Parameter: Data (Measure/Generate)  : chan0Data
    {1000, 1000,  OFFSET(chan0Data), "chan0Data", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Raw Data : chan0RawData
    {1002, 1000,  OFFSET(chan0RawData), "chan0RawData", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan0ResultCjValue
    {1004, 1000,  OFFSET(chan0ResultCjValue), "chan0ResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data flags : chan0DataFlags
    {1006, 1000,  OFFSET(chan0DataFlags), "chan0DataFlags", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan0Status
    {1007, 1000,  OFFSET(chan0Status), "chan0Status", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Error channel : chan0Error
    {1008, 1000,  OFFSET(chan0Error), "chan0Error", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Uptime  : chan0Uptime
    {1009, 1000,  OFFSET(chan0Uptime), "chan0Uptime", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Signal Type : chan0SignalType
    {1011, 1000,  OFFSET(chan0SignalType), "chan0SignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter1 : chan0AdditionalParameter1
    {1012, 1000,  OFFSET(chan0AdditionalParameter1), "chan0AdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter2 : chan0AdditionalParameter2
    {1018, 1000,  OFFSET(chan0AdditionalParameter2), "chan0AdditionalParameter2", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal low limit  : chan0TransferSignalLowLim
    {1024, 1000,  OFFSET(chan0TransferSignalLowLim), "chan0TransferSignalLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal high limit  : chan0TransferSignalHighLim
    {1026, 1000,  OFFSET(chan0TransferSignalHighLim), "chan0TransferSignalHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale low limit  : chan0TransferScaleLowLim
    {1028, 1000,  OFFSET(chan0TransferScaleLowLim), "chan0TransferScaleLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale high limit  : chan0TransferScaleHighLim
    {1030, 1000,  OFFSET(chan0TransferScaleHighLim), "chan0TransferScaleHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correction CJ Value : chan0CorrectionCjValue
    {1032, 1000,  OFFSET(chan0CorrectionCjValue), "chan0CorrectionCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Data (Measure/Generate)  : chan1Data
    {2000, 1000,  OFFSET(chan1Data), "chan1Data", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Raw Data : chan1RawData
    {2002, 1000,  OFFSET(chan1RawData), "chan1RawData", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan1ResultCjValue
    {2004, 1000,  OFFSET(chan1ResultCjValue), "chan1ResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data flags : chan1DataFlags
    {2006, 1000,  OFFSET(chan1DataFlags), "chan1DataFlags", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan1Status
    {2007, 1000,  OFFSET(chan1Status), "chan1Status", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Error channel : chan1Error
    {2008, 1000,  OFFSET(chan1Error), "chan1Error", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Uptime  : chan1Uptime
    {2009, 1000,  OFFSET(chan1Uptime), "chan1Uptime", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Signal Type : chan1SignalType
    {2011, 1000,  OFFSET(chan1SignalType), "chan1SignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter1 : chan1AdditionalParameter1
    {2012, 1000,  OFFSET(chan1AdditionalParameter1), "chan1AdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter2 : chan1AdditionalParameter2
    {2018, 1000,  OFFSET(chan1AdditionalParameter2), "chan1AdditionalParameter2", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal low limit  : chan1TransferSignalLowLim
    {2024, 1000,  OFFSET(chan1TransferSignalLowLim), "chan1TransferSignalLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal high limit  : chan1TransferSignalHighLim
    {2026, 1000,  OFFSET(chan1TransferSignalHighLim), "chan1TransferSignalHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale low limit  : chan1TransferScaleLowLim
    {2028, 1000,  OFFSET(chan1TransferScaleLowLim), "chan1TransferScaleLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale high limit  : chan1TransferScaleHighLim
    {2030, 1000,  OFFSET(chan1TransferScaleHighLim), "chan1TransferScaleHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan1CorrectionCjValue
    {2032, 1000,  OFFSET(chan1CorrectionCjValue), "chan1CorrectionCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Data (Measure/Generate)  : chan2Data
    {3000, 1000,  OFFSET(chan2Data), "chan2Data", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Raw Data : chan2RawData
    {3002, 1000,  OFFSET(chan2RawData), "chan2RawData", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan2ResultCjValue
    {3004, 1000,  OFFSET(chan2ResultCjValue), "chan2ResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data flags : chan2DataFlags
    {3006, 1000,  OFFSET(chan2DataFlags), "chan2DataFlags", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan2Status
    {3007, 1000,  OFFSET(chan2Status), "chan2Status", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Error channel : chan2Error
    {3008, 1000,  OFFSET(chan2Error), "chan2Error", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Uptime  : chan2Uptime
    {3009, 1000,  OFFSET(chan2Uptime), "chan2Uptime", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Signal Type : chan2SignalType
    {3011, 1000,  OFFSET(chan2SignalType), "chan2SignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter1 : chan2AdditionalParameter1
    {3012, 1000,  OFFSET(chan2AdditionalParameter1), "chan2AdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter2 : chan2AdditionalParameter2
    {3018, 1000,  OFFSET(chan2AdditionalParameter2), "chan2AdditionalParameter2", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal low limit  : chan2TransferSignalLowLim
    {3024, 1000,  OFFSET(chan2TransferSignalLowLim), "chan2TransferSignalLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal high limit  : chan2TransferSignalHighLim
    {3026, 1000,  OFFSET(chan2TransferSignalHighLim), "chan2TransferSignalHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale low limit  : chan2TransferScaleLowLim
    {3028, 1000,  OFFSET(chan2TransferScaleLowLim), "chan2TransferScaleLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale high limit  : chan2TransferScaleHighLim
    {3030, 1000,  OFFSET(chan2TransferScaleHighLim), "chan2TransferScaleHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan2CorrectionCjValue
    {3032, 1000,  OFFSET(chan2CorrectionCjValue), "chan2CorrectionCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Data (Measure/Generate)  : chan3Data
    {4000, 1000,  OFFSET(chan3Data), "chan3Data", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Raw Data : chan3RawData
    {4002, 1000,  OFFSET(chan3RawData), "chan3RawData", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan3ResultCjValue
    {4004, 1000,  OFFSET(chan3ResultCjValue), "chan3ResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Data flags : chan3DataFlags
    {4006, 1000,  OFFSET(chan3DataFlags), "chan3DataFlags", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan3Status
    {4007, 1000,  OFFSET(chan3Status), "chan3Status", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Error channel : chan3Error
    {4008, 1000,  OFFSET(chan3Error), "chan3Error", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Uptime  : chan3Uptime
    {4009, 1000,  OFFSET(chan3Uptime), "chan3Uptime", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Signal Type : chan3SignalType
    {4011, 1000,  OFFSET(chan3SignalType), "chan3SignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter1 : chan3AdditionalParameter1
    {4012, 1000,  OFFSET(chan3AdditionalParameter1), "chan3AdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter2 : chan3AdditionalParameter2
    {4018, 1000,  OFFSET(chan3AdditionalParameter2), "chan3AdditionalParameter2", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal low limit  : chan3TransferSignalLowLim
    {4024, 1000,  OFFSET(chan3TransferSignalLowLim), "chan3TransferSignalLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer signal high limit  : chan3TransferSignalHighLim
    {4026, 1000,  OFFSET(chan3TransferSignalHighLim), "chan3TransferSignalHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale low limit  : chan3TransferScaleLowLim
    {4028, 1000,  OFFSET(chan3TransferScaleLowLim), "chan3TransferScaleLowLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Transfer scale High limit  : chan3TransferScaleHighLim
    {4030, 1000,  OFFSET(chan3TransferScaleHighLim), "chan3TransferScaleHighLim", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan3CorrectionCjValue
    {4032, 1000,  OFFSET(chan3CorrectionCjValue), "chan3CorrectionCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Temperature square : chan0TempSquare
    {5000, 1000,  OFFSET(chan0TempSquare), "chan0TempSquare", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Senson activity oxygen : chan0PrimaryActivity
    {5002, 1000,  OFFSET(chan0PrimaryActivity), "chan0PrimaryActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan0SteelResultCjValue
    {5004, 1000,  OFFSET(chan0SteelResultCjValue), "chan0SteelResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Oxygen_activity : chan0OxActivity
    {5006, 1000,  OFFSET(chan0OxActivity), "chan0OxActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Mass_Aluminium : chan0MassAl
    {5008, 1000,  OFFSET(chan0MassAl), "chan0MassAl", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Сarbon_сontent : chan0Carbon
    {5010, 1000,  OFFSET(chan0Carbon), "chan0Carbon", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan0SteelStatus
    {5012, 1000,  OFFSET(chan0SteelStatus), "chan0SteelStatus", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Channel Error : chan0SteelError
    {5013, 1000,  OFFSET(chan0SteelError), "chan0SteelError", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Additional parameter1 : chan0SteelAdditionalParameter1
    {5014, 500,  OFFSET(chan0SteelAdditionalParameter1), "chan0SteelAdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Verification read Master : chan0VerificationRead
    {5020, 500,  OFFSET(chan0VerificationRead), "chan0VerificationRead", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan0SteelCorrectionjValue
    {5022, 500,  OFFSET(chan0SteelCorrectionjValue), "chan0SteelCorrectionjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_measure : chan0TimeMeasure
    {5024, 1000,  OFFSET(chan0TimeMeasure), "chan0TimeMeasure", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_temperature : chan0RangeTemp
    {5026, 1000,  OFFSET(chan0RangeTemp), "chan0RangeTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_temperature : chan0TimeSquareTemp
    {5028, 1000,  OFFSET(chan0TimeSquareTemp), "chan0TimeSquareTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Low_lim_temp : chan0LowTemp
    {5030, 1000,  OFFSET(chan0LowTemp), "chan0LowTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Hi_lim_temp : chan0HiTemp
    {5032, 1000,  OFFSET(chan0HiTemp), "chan0HiTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Sensor_Type_Activty : chan0SensorType
    {5034, 1000,  OFFSET(chan0SensorType), "chan0SensorType", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_EDS : chan0TimeSquareEDS
    {5036, 1000,  OFFSET(chan0TimeSquareEDS), "chan0TimeSquareEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_EDS : chan0RangeEDS
    {5038, 1000,  OFFSET(chan0RangeEDS), "chan0RangeEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Сrystallization_temperature : chan0Crystallization
    {5040, 1000,  OFFSET(chan0Crystallization), "chan0Crystallization", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_coefficient : chan0MassCoeff
    {5042, 1000,  OFFSET(chan0MassCoeff), "chan0MassCoeff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Final_oxidation : chan0FinalOx
    {5044, 1000,  OFFSET(chan0FinalOx), "chan0FinalOx", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Assimilation of aluminum : chan0Assimilation
    {5046, 1000,  OFFSET(chan0Assimilation), "chan0Assimilation", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_melting : chan0MassMelting
    {5048, 1000,  OFFSET(chan0MassMelting), "chan0MassMelting", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TEMP array0 : chan0TEMParray0
    {5050, 1000,  OFFSET(chan0TEMParray0), "chan0TEMParray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array1 : chan0TEMParray1
    {5082, 1000,  OFFSET(chan0TEMParray1), "chan0TEMParray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array2 : chan0TEMParray2
    {5114, 1000,  OFFSET(chan0TEMParray2), "chan0TEMParray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array3 : chan0TEMParray3
    {5146, 1000,  OFFSET(chan0TEMParray3), "chan0TEMParray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array4 : chan0TEMParray4
    {5178, 1000,  OFFSET(chan0TEMParray4), "chan0TEMParray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array0 : chan0EMFarray0
    {5210, 1000,  OFFSET(chan0EMFarray0), "chan0EMFarray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array1 : chan0EMFarray1
    {5242, 1000,  OFFSET(chan0EMFarray1), "chan0EMFarray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array2 : chan0EMFarray2
    {5274, 1000,  OFFSET(chan0EMFarray2), "chan0EMFarray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array3 : chan0EMFarray3
    {5306, 1000,  OFFSET(chan0EMFarray3), "chan0EMFarray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array4 : chan0EMFarray4
    {5338, 1000,  OFFSET(chan0EMFarray4), "chan0EMFarray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Temperature square : chan1TempSquare
    {6000, 1000,  OFFSET(chan1TempSquare), "chan1TempSquare", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Senson activity oxygen : chan1PrimaryActivity
    {6002, 1000,  OFFSET(chan1PrimaryActivity), "chan1PrimaryActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan1SteelResultCjValue
    {6004, 1000,  OFFSET(chan1SteelResultCjValue), "chan1SteelResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Oxygen_activity : chan1OxActivity
    {6006, 1000,  OFFSET(chan1OxActivity), "chan1OxActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Mass_Aluminium : chan1MassAl
    {6008, 1000,  OFFSET(chan1MassAl), "chan1MassAl", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Сarbon_сontent : chan1Carbon
    {6010, 1000,  OFFSET(chan1Carbon), "chan1Carbon", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan1SteelStatus
    {6012, 1000,  OFFSET(chan1SteelStatus), "chan1SteelStatus", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Channel Error : chan1SteelError
    {6013, 1000,  OFFSET(chan1SteelError), "chan1SteelError", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Additional parameter1 : chan1SteelAdditionalParameter1
    {6014, 1000,  OFFSET(chan1SteelAdditionalParameter1), "chan1SteelAdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Verification read Master : chan1VerificationRead
    {6020, 1000,  OFFSET(chan1VerificationRead), "chan1VerificationRead", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan1SteelCorrectionjValue
    {6022, 1000,  OFFSET(chan1SteelCorrectionjValue), "chan1SteelCorrectionjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_measure : chan1TimeMeasure
    {6024, 1000,  OFFSET(chan1TimeMeasure), "chan1TimeMeasure", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_temperature : chan1RangeTemp
    {6026, 1000,  OFFSET(chan1RangeTemp), "chan1RangeTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_temperature : chan1TimeSquareTemp
    {6028, 1000,  OFFSET(chan1TimeSquareTemp), "chan1TimeSquareTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Low_lim_temp : chan1LowTemp
    {6030, 1000,  OFFSET(chan1LowTemp), "chan1LowTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Hi_lim_temp : chan1HiTemp
    {6032, 1000,  OFFSET(chan1HiTemp), "chan1HiTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Sensor_Type_Activty : chan1SensorType
    {6034, 1000,  OFFSET(chan1SensorType), "chan1SensorType", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_EDS : chan1TimeSquareEDS
    {6036, 1000,  OFFSET(chan1TimeSquareEDS), "chan1TimeSquareEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_EDS : chan1RangeEDS
    {6038, 1000,  OFFSET(chan1RangeEDS), "chan1RangeEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Сrystallization_temperature : chan1Crystallization
    {6040, 1000,  OFFSET(chan1Crystallization), "chan1Crystallization", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_coefficient : chan1MassCoeff
    {6042, 1000,  OFFSET(chan1MassCoeff), "chan1MassCoeff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Final_oxidation : chan1FinalOx
    {6044, 1000,  OFFSET(chan1FinalOx), "chan1FinalOx", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Assimilation of aluminum : chan1Assimilation
    {6046, 1000,  OFFSET(chan1Assimilation), "chan1Assimilation", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_melting : chan1MassMelting
    {6048, 1000,  OFFSET(chan1MassMelting), "chan1MassMelting", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TEMP array0 : chan1TEMParray0
    {6050, 1000,  OFFSET(chan1TEMParray0), "chan1TEMParray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array1 : chan1TEMParray1
    {6082, 1000,  OFFSET(chan1TEMParray1), "chan1TEMParray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array2 : chan1TEMParray2
    {6114, 1000,  OFFSET(chan1TEMParray2), "chan1TEMParray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array3 : chan1TEMParray3
    {6146, 1000,  OFFSET(chan1TEMParray3), "chan1TEMParray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array4 : chan1TEMParray4
    {6178, 1000,  OFFSET(chan1TEMParray4), "chan1TEMParray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array0 : chan1EMFarray0
    {6210, 1000,  OFFSET(chan1EMFarray0), "chan1EMFarray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array1 : chan1EMFarray1
    {6242, 1000,  OFFSET(chan1EMFarray1), "chan1EMFarray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array2 : chan1EMFarray2
    {6274, 1000,  OFFSET(chan1EMFarray2), "chan1EMFarray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array3 : chan1EMFarray3
    {6306, 1000,  OFFSET(chan1EMFarray3), "chan1EMFarray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array4 : chan1EMFarray4
    {6338, 1000,  OFFSET(chan1EMFarray4), "chan1EMFarray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Temperature square : chan2TempSquare
    {7000, 1000,  OFFSET(chan2TempSquare), "chan2TempSquare", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Senson activity oxygen : chan2PrimaryActivity
    {7002, 1000,  OFFSET(chan2PrimaryActivity), "chan2PrimaryActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan2SteelResultCjValue
    {7004, 1000,  OFFSET(chan2SteelResultCjValue), "chan2SteelResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Oxygen_activity : chan2OxActivity
    {7006, 1000,  OFFSET(chan2OxActivity), "chan2OxActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Mass_Aluminium : chan2MassAl
    {7008, 1000,  OFFSET(chan2MassAl), "chan2MassAl", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Сarbon_сontent : chan2Carbon
    {7010, 1000,  OFFSET(chan2Carbon), "chan2Carbon", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan2SteelStatus
    {7012, 1000,  OFFSET(chan2SteelStatus), "chan2SteelStatus", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Channel Error : chan2SteelError
    {7013, 1000,  OFFSET(chan2SteelError), "chan2SteelError", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Additional parameter1 : chan2SteelAdditionalParameter1
    {7014, 500,  OFFSET(chan2SteelAdditionalParameter1), "chan2SteelAdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Verification read Master : chan2VerificationRead
    {7020, 500,  OFFSET(chan2VerificationRead), "chan2VerificationRead", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan2SteelCorrectionjValue
    {7022, 500,  OFFSET(chan2SteelCorrectionjValue), "chan2SteelCorrectionjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_measure : chan2TimeMeasure
    {7024, 1000,  OFFSET(chan2TimeMeasure), "chan2TimeMeasure", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_temperature : chan2RangeTemp
    {7026, 1000,  OFFSET(chan2RangeTemp), "chan2RangeTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_temperature : chan2TimeSquareTemp
    {7028, 1000,  OFFSET(chan2TimeSquareTemp), "chan2TimeSquareTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Low_lim_temp : chan2LowTemp
    {7030, 1000,  OFFSET(chan2LowTemp), "chan2LowTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Hi_lim_temp : chan2HiTemp
    {7032, 1000,  OFFSET(chan2HiTemp), "chan2HiTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Sensor_Type_Activty : chan2SensorType
    {7034, 1000,  OFFSET(chan2SensorType), "chan2SensorType", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_EDS : chan2TimeSquareEDS
    {7036, 1000,  OFFSET(chan2TimeSquareEDS), "chan2TimeSquareEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_EDS : chan2RangeEDS
    {7038, 1000,  OFFSET(chan2RangeEDS), "chan2RangeEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Сrystallization_temperature : chan2Crystallization
    {7040, 1000,  OFFSET(chan2Crystallization), "chan2Crystallization", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_coefficient : chan2MassCoeff
    {7042, 1000,  OFFSET(chan2MassCoeff), "chan2MassCoeff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Final_oxidation : chan2FinalOx
    {7044, 1000,  OFFSET(chan2FinalOx), "chan2FinalOx", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Assimilation of aluminum : chan2Assimilation
    {7046, 1000,  OFFSET(chan2Assimilation), "chan2Assimilation", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_melting : chan2MassMelting
    {7048, 1000,  OFFSET(chan2MassMelting), "chan2MassMelting", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TEMP array0 : chan2TEMParray0
    {7050, 1000,  OFFSET(chan2TEMParray0), "chan2TEMParray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array1 : chan2TEMParray1
    {7082, 1000,  OFFSET(chan2TEMParray1), "chan2TEMParray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array2 : chan2TEMParray2
    {7114, 1000,  OFFSET(chan2TEMParray2), "chan2TEMParray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array3 : chan2TEMParray3
    {7146, 1000,  OFFSET(chan2TEMParray3), "chan2TEMParray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array4 : chan2TEMParray4
    {7178, 1000,  OFFSET(chan2TEMParray4), "chan2TEMParray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array0 : chan2EMFarray0
    {7210, 1000,  OFFSET(chan2EMFarray0), "chan2EMFarray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array1 : chan2EMFarray1
    {7242, 1000,  OFFSET(chan2EMFarray1), "chan2EMFarray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array2 : chan2EMFarray2
    {7274, 1000,  OFFSET(chan2EMFarray2), "chan2EMFarray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array3 : chan2EMFarray3
    {7306, 1000,  OFFSET(chan2EMFarray3), "chan2EMFarray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array4 : chan2EMFarray4
    {7338, 1000,  OFFSET(chan2EMFarray4), "chan2EMFarray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Temperature square : chan3TempSquare
    {8000, 1000,  OFFSET(chan3TempSquare), "chan3TempSquare", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Senson activity oxygen : chan3PrimaryActivity
    {8002, 1000,  OFFSET(chan3PrimaryActivity), "chan3PrimaryActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Result CJ Value : chan3SteelResultCjValue
    {8004, 1000,  OFFSET(chan3SteelResultCjValue), "chan3SteelResultCjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Oxygen_activity : chan3OxActivity
    {8006, 1000,  OFFSET(chan3OxActivity), "chan3OxActivity", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Mass_Aluminium : chan3MassAl
    {8008, 1000,  OFFSET(chan3MassAl), "chan3MassAl", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Сarbon_сontent : chan3Carbon
    {8010, 1000,  OFFSET(chan3Carbon), "chan3Carbon", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Status : chan3SteelStatus
    {8012, 1000,  OFFSET(chan3SteelStatus), "chan3SteelStatus", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Channel Error : chan3SteelError
    {8013, 1000,  OFFSET(chan3SteelError), "chan3SteelError", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Additional parameter1 : chan3SteelAdditionalParameter1
    {8014, 500,  OFFSET(chan3SteelAdditionalParameter1), "chan3SteelAdditionalParameter1", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Verification read Master : chan3VerificationRead
    {8020, 500,  OFFSET(chan3VerificationRead), "chan3VerificationRead", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Correctrion CJ Value : chan3SteelCorrectionjValue
    {8022, 500,  OFFSET(chan3SteelCorrectionjValue), "chan3SteelCorrectionjValue", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_measure : chan3TimeMeasure
    {8024, 1000,  OFFSET(chan3TimeMeasure), "chan3TimeMeasure", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_temperature : chan3RangeTemp
    {8026, 1000,  OFFSET(chan3RangeTemp), "chan3RangeTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_temperature : chan3TimeSquareTemp
    {8028, 1000,  OFFSET(chan3TimeSquareTemp), "chan3TimeSquareTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Low_lim_temp : chan3LowTemp
    {8030, 1000,  OFFSET(chan3LowTemp), "chan3LowTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Hi_lim_temp : chan3HiTemp
    {8032, 1000,  OFFSET(chan3HiTemp), "chan3HiTemp", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Sensor_Type_Activty : chan3SensorType
    {8034, 1000,  OFFSET(chan3SensorType), "chan3SensorType", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Time_square_EDS : chan3TimeSquareEDS
    {8036, 1000,  OFFSET(chan3TimeSquareEDS), "chan3TimeSquareEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Range_EDS : chan3RangeEDS
    {8038, 1000,  OFFSET(chan3RangeEDS), "chan3RangeEDS", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Сrystallization_temperature : chan3Crystallization
    {8040, 1000,  OFFSET(chan3Crystallization), "chan3Crystallization", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_coefficient : chan3MassCoeff
    {8042, 1000,  OFFSET(chan3MassCoeff), "chan3MassCoeff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Final_oxidation : chan3FinalOx
    {8044, 1000,  OFFSET(chan3FinalOx), "chan3FinalOx", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Assimilation of aluminum : chan3Assimilation
    {8046, 1000,  OFFSET(chan3Assimilation), "chan3Assimilation", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Mass_melting : chan3MassMelting
    {8048, 1000,  OFFSET(chan3MassMelting), "chan3MassMelting", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TEMP array0 : chan3TEMParray0
    {8050, 1000,  OFFSET(chan3TEMParray0), "chan3TEMParray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array1 : chan3TEMParray1
    {8082, 1000,  OFFSET(chan3TEMParray1), "chan3TEMParray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array2 : chan3TEMParray2
    {8114, 1000,  OFFSET(chan3TEMParray2), "chan3TEMParray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array3 : chan3TEMParray3
    {8146, 1000,  OFFSET(chan3TEMParray3), "chan3TEMParray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: TEMP array4 : chan3TEMParray4
    {8178, 1000,  OFFSET(chan3TEMParray4), "chan3TEMParray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array0 : chan3EMFarray0
    {8210, 1000,  OFFSET(chan3EMFarray0), "chan3EMFarray0", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array1 : chan3EMFarray1
    {8242, 1000,  OFFSET(chan3EMFarray1), "chan3EMFarray1", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array2 : chan3EMFarray2
    {8274, 1000,  OFFSET(chan3EMFarray2), "chan3EMFarray2", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array3 : chan3EMFarray3
    {8306, 1000,  OFFSET(chan3EMFarray3), "chan3EMFarray3", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: EMF array4 : chan3EMFarray4
    {8338, 1000,  OFFSET(chan3EMFarray4), "chan3EMFarray4", LKUP_TYPE_ASCII, 64, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Hi alarm_Reley : RelayControl
    {9000, 1000,  OFFSET(RelayControl), "RelayControl", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan0MeasureFreq
    {10000, 1000,  OFFSET(chan0MeasureFreq), "chan0MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan0Impulse
    {10002, 1000,  OFFSET(chan0Impulse), "chan0Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan0ImpulseBuff
    {10004, 1004,  OFFSET(chan0ImpulseBuff), "chan0ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan0DigitSignalType
    {10006, 1004,  OFFSET(chan0DigitSignalType), "chan0DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan0DigitalAdditionalParameter
    {10007, 1004,  OFFSET(chan0DigitalAdditionalParameter), "chan0DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan0ImpulseDuration
    {10013, 1004,  OFFSET(chan0ImpulseDuration), "chan0ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan1MeasureFreq
    {11000, 1004,  OFFSET(chan1MeasureFreq), "chan1MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan1Impulse
    {11002, 1004,  OFFSET(chan1Impulse), "chan1Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan1ImpulseBuff
    {11004, 1008,  OFFSET(chan1ImpulseBuff), "chan1ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan1DigitSignalType
    {11006, 1008,  OFFSET(chan1DigitSignalType), "chan1DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan1DigitalAdditionalParameter
    {11007, 1008,  OFFSET(chan1DigitalAdditionalParameter), "chan1DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan1ImpulseDuration
    {11013, 1008,  OFFSET(chan1ImpulseDuration), "chan1ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan2MeasureFreq
    {12000, 1008,  OFFSET(chan2MeasureFreq), "chan2MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan2Impulse
    {12002, 1008,  OFFSET(chan2Impulse), "chan2Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan2ImpulseBuff
    {12004, 1012,  OFFSET(chan2ImpulseBuff), "chan2ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan2DigitSignalType
    {12006, 1012,  OFFSET(chan2DigitSignalType), "chan2DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan2DigitalAdditionalParameter
    {12007, 1012,  OFFSET(chan2DigitalAdditionalParameter), "chan2DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan2ImpulseDuration
    {12013, 1012,  OFFSET(chan2ImpulseDuration), "chan2ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan3MeasureFreq
    {13000, 1012,  OFFSET(chan3MeasureFreq), "chan3MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan3Impulse
    {13002, 1012,  OFFSET(chan3Impulse), "chan3Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan3ImpulseBuff
    {13004, 1016,  OFFSET(chan3ImpulseBuff), "chan3ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan3DigitSignalType
    {13006, 1016,  OFFSET(chan3DigitSignalType), "chan3DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan3DigitalAdditionalParameter
    {13007, 1016,  OFFSET(chan3DigitalAdditionalParameter), "chan3DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan3ImpulseDuration
    {13013, 1016,  OFFSET(chan3ImpulseDuration), "chan3ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan4MeasureFreq
    {14000, 1016,  OFFSET(chan4MeasureFreq), "chan4MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan4Impulse
    {14002, 1016,  OFFSET(chan4Impulse), "chan4Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan4ImpulseBuff
    {14004, 1020,  OFFSET(chan4ImpulseBuff), "chan4ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan4DigitSignalType
    {14006, 1020,  OFFSET(chan4DigitSignalType), "chan4DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan4DigitalAdditionalParameter
    {14007, 1020,  OFFSET(chan4DigitalAdditionalParameter), "chan4DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan4ImpulseDuration
    {14013, 1020,  OFFSET(chan4ImpulseDuration), "chan4ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Out freq chan : chan5MeasureFreq
    {15000, 1020,  OFFSET(chan5MeasureFreq), "chan5MeasureFreq", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: Out  imp chan : chan5Impulse
    {15002, 1020,  OFFSET(chan5Impulse), "chan5Impulse", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R},
    // Parameter: Buffer impulse : chan5ImpulseBuff
    {15004, 1024,  OFFSET(chan5ImpulseBuff), "chan5ImpulseBuff", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R},
    // Parameter: SignalType(Digital) : chan5DigitSignalType
    {15006, 1024,  OFFSET(chan5DigitSignalType), "chan5DigitSignalType", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: Additional parameter : chan5DigitalAdditionalParameter
    {15007, 1024,  OFFSET(chan5DigitalAdditionalParameter), "chan5DigitalAdditionalParameter", LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: TimeDamping : chan5ImpulseDuration
    {15013, 1024,  OFFSET(chan5ImpulseDuration), "chan5ImpulseDuration", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW},
    // Parameter: SysOCalb : chan0SysOCR
    {60000, 100,  OFFSET(chan0SysOCR), "chan0SysOCR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysGCalb : chan0SysFSR
    {60001, 100,  OFFSET(chan0SysFSR), "chan0SysFSR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mV : chan0OCR20mV
    {60002, 100,  OFFSET(chan0OCR20mV), "chan0OCR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mV : chan0FSR20mV
    {60004, 104,  OFFSET(chan0FSR20mV), "chan0FSR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mV : chan0Date20mV
    {60006, 108,  OFFSET(chan0Date20mV), "chan0Date20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR100mV : chan0OCR100mV
    {60008, 112,  OFFSET(chan0OCR100mV), "chan0OCR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR100mV : chan0FSR100mV
    {60010, 116,  OFFSET(chan0FSR100mV), "chan0FSR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate100mV : chan0Date100mV
    {60012, 120,  OFFSET(chan0Date100mV), "chan0Date100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR1V : chan0OCR1V
    {60014, 124,  OFFSET(chan0OCR1V), "chan0OCR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR1V : chan0FSR1V
    {60016, 128,  OFFSET(chan0FSR1V), "chan0FSR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate1V : chan0Date1V
    {60018, 132,  OFFSET(chan0Date1V), "chan0Date1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR10V : chan0OCR10V
    {60020, 136,  OFFSET(chan0OCR10V), "chan0OCR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR10V : chan0FSR10V
    {60022, 140,  OFFSET(chan0FSR10V), "chan0FSR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate10V : chan0Date10V
    {60024, 144,  OFFSET(chan0Date10V), "chan0Date10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR30V : chan0OCR30V
    {60026, 148,  OFFSET(chan0OCR30V), "chan0OCR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR30V : chan0FSR30V
    {60028, 152,  OFFSET(chan0FSR30V), "chan0FSR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate30V : chan0Date30V
    {60030, 156,  OFFSET(chan0Date30V), "chan0Date30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mA : chan0OCR20mA
    {60032, 160,  OFFSET(chan0OCR20mA), "chan0OCR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mA : chan0FSR20mA
    {60034, 164,  OFFSET(chan0FSR20mA), "chan0FSR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mA : chan0Date20mA
    {60036, 168,  OFFSET(chan0Date20mA), "chan0Date20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR4x : chan0OCR4x
    {60038, 172,  OFFSET(chan0OCR4x), "chan0OCR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR4x : chan0FSR4x
    {60040, 176,  OFFSET(chan0FSR4x), "chan0FSR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate4x : chan0Date4x
    {60042, 180,  OFFSET(chan0Date4x), "chan0Date4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR3x : chan0OCR3x
    {60044, 184,  OFFSET(chan0OCR3x), "chan0OCR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR3x : chan0FSR3x
    {60046, 188,  OFFSET(chan0FSR3x), "chan0FSR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate3x : chan0Date3x
    {60048, 192,  OFFSET(chan0Date3x), "chan0Date3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCRinternal : chan0OCRinternal
    {60050, 196,  OFFSET(chan0OCRinternal), "chan0OCRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSRinternal : chan0FSRinternal
    {60052, 200,  OFFSET(chan0FSRinternal), "chan0FSRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDateinternal : chan0DateInternal
    {60054, 204,  OFFSET(chan0DateInternal), "chan0DateInternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysOCalb : chan1SysOCR
    {60100, 208,  OFFSET(chan1SysOCR), "chan1SysOCR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysGCalb : chan1SysFSR
    {60101, 208,  OFFSET(chan1SysFSR), "chan1SysFSR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mV : chan1OCR20mV
    {60102, 208,  OFFSET(chan1OCR20mV), "chan1OCR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mV : chan1FSR20mV
    {60104, 212,  OFFSET(chan1FSR20mV), "chan1FSR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mV : chan1Date20mV
    {60106, 216,  OFFSET(chan1Date20mV), "chan1Date20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR100mV : chan1OCR100mV
    {60108, 220,  OFFSET(chan1OCR100mV), "chan1OCR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR100mV : chan1FSR100mV
    {60110, 224,  OFFSET(chan1FSR100mV), "chan1FSR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate100mV : chan1Date100mV
    {60112, 228,  OFFSET(chan1Date100mV), "chan1Date100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR1V : chan1OCR1V
    {60114, 232,  OFFSET(chan1OCR1V), "chan1OCR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR1V : chan1FSR1V
    {60116, 236,  OFFSET(chan1FSR1V), "chan1FSR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate1V : chan1Date1V
    {60118, 240,  OFFSET(chan1Date1V), "chan1Date1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR10V : chan1OCR10V
    {60120, 244,  OFFSET(chan1OCR10V), "chan1OCR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR10V : chan1FSR10V
    {60122, 248,  OFFSET(chan1FSR10V), "chan1FSR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate10V : chan1Date10V
    {60124, 252,  OFFSET(chan1Date10V), "chan1Date10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR30V : chan1OCR30V
    {60126, 256,  OFFSET(chan1OCR30V), "chan1OCR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR30V : chan1FSR30V
    {60128, 260,  OFFSET(chan1FSR30V), "chan1FSR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate30V : chan1Date30V
    {60130, 264,  OFFSET(chan1Date30V), "chan1Date30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mA : chan1OCR20mA
    {60132, 268,  OFFSET(chan1OCR20mA), "chan1OCR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mA : chan1FSR20mA
    {60134, 272,  OFFSET(chan1FSR20mA), "chan1FSR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mA : chan1Date20mA
    {60136, 276,  OFFSET(chan1Date20mA), "chan1Date20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR4x : chan1OCR4x
    {60138, 280,  OFFSET(chan1OCR4x), "chan1OCR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR4x : chan1FSR4x
    {60140, 284,  OFFSET(chan1FSR4x), "chan1FSR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate4x : chan1Date4x
    {60142, 288,  OFFSET(chan1Date4x), "chan1Date4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR3x : chan1OCR3x
    {60144, 292,  OFFSET(chan1OCR3x), "chan1OCR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR3x : chan1FSR3x
    {60146, 296,  OFFSET(chan1FSR3x), "chan1FSR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate3x : chan1Date3x
    {60148, 300,  OFFSET(chan1Date3x), "chan1Date3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCRinternal : chan1OCRinternal
    {60150, 304,  OFFSET(chan1OCRinternal), "chan1OCRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSRinternal : chan1FSRinternal
    {60152, 308,  OFFSET(chan1FSRinternal), "chan1FSRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDateinternal : chan1DateInternal
    {60154, 312,  OFFSET(chan1DateInternal), "chan1DateInternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysOCalb : chan2SysOCR
    {60200, 316,  OFFSET(chan2SysOCR), "chan2SysOCR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysGCalb : chan2SysFSR
    {60201, 316,  OFFSET(chan2SysFSR), "chan2SysFSR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mV : chan2OCR20mV
    {60202, 316,  OFFSET(chan2OCR20mV), "chan2OCR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mV : chan2FSR20mV
    {60204, 320,  OFFSET(chan2FSR20mV), "chan2FSR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mV : chan2Date20mV
    {60206, 324,  OFFSET(chan2Date20mV), "chan2Date20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR100mV : chan2OCR100mV
    {60208, 328,  OFFSET(chan2OCR100mV), "chan2OCR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR100mV : chan2FSR100mV
    {60210, 332,  OFFSET(chan2FSR100mV), "chan2FSR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate100mV : chan2Date100mV
    {60212, 336,  OFFSET(chan2Date100mV), "chan2Date100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR1V : chan2OCR1V
    {60214, 340,  OFFSET(chan2OCR1V), "chan2OCR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR1V : chan2FSR1V
    {60216, 344,  OFFSET(chan2FSR1V), "chan2FSR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate1V : chan2Date1V
    {60218, 348,  OFFSET(chan2Date1V), "chan2Date1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR10V : chan2OCR10V
    {60220, 352,  OFFSET(chan2OCR10V), "chan2OCR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR10V : chan2FSR10V
    {60222, 356,  OFFSET(chan2FSR10V), "chan2FSR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate10V : chan2Date10V
    {60224, 360,  OFFSET(chan2Date10V), "chan2Date10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR30V : chan2OCR30V
    {60226, 364,  OFFSET(chan2OCR30V), "chan2OCR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR30V : chan2FSR30V
    {60228, 368,  OFFSET(chan2FSR30V), "chan2FSR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate30V : chan2Date30V
    {60230, 372,  OFFSET(chan2Date30V), "chan2Date30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mA : chan2OCR20mA
    {60232, 376,  OFFSET(chan2OCR20mA), "chan2OCR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mA : chan2FSR20mA
    {60234, 380,  OFFSET(chan2FSR20mA), "chan2FSR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mA : chan2Date20mA
    {60236, 384,  OFFSET(chan2Date20mA), "chan2Date20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR4x : chan2OCR4x
    {60238, 388,  OFFSET(chan2OCR4x), "chan2OCR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR4x : chan2FSR4x
    {60240, 392,  OFFSET(chan2FSR4x), "chan2FSR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate4x : chan2Date4x
    {60242, 396,  OFFSET(chan2Date4x), "chan2Date4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR3x : chan2OCR3x
    {60244, 400,  OFFSET(chan2OCR3x), "chan2OCR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR3x : chan2FSR3x
    {60246, 404,  OFFSET(chan2FSR3x), "chan2FSR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate3x : chan2Date3x
    {60248, 408,  OFFSET(chan2Date3x), "chan2Date3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCRinternal : chan2OCRinternal
    {60250, 412,  OFFSET(chan2OCRinternal), "chan2OCRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSRinternal : chan2FSRinternal
    {60252, 416,  OFFSET(chan2FSRinternal), "chan2FSRinternal", LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDateinternal : chan2DateInternal
    {60254, 420,  OFFSET(chan2DateInternal), "chan2DateInternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysOCalb : chan3SysOCR
    {60300, 424,  OFFSET(chan3SysOCR), "chan3SysOCR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: SysGCalb : chan3SysFSR
    {60301, 424,  OFFSET(chan3SysFSR), "chan3SysFSR", LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mV : chan3OCR20mV
    {60302, 424,  OFFSET(chan3OCR20mV), "chan3OCR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mV : chan3FSR20mV
    {60304, 428,  OFFSET(chan3FSR20mV), "chan3FSR20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mV : chan3Date20mV
    {60306, 432,  OFFSET(chan3Date20mV), "chan3Date20mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR100mV : chan3OCR100mV
    {60308, 436,  OFFSET(chan3OCR100mV), "chan3OCR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR100mV : chan3FSR100mV
    {60310, 440,  OFFSET(chan3FSR100mV), "chan3FSR100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate100mV : chan3Date100mV
    {60312, 444,  OFFSET(chan3Date100mV), "chan3Date100mV", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR1V : chan3OCR1V
    {60314, 448,  OFFSET(chan3OCR1V), "chan3OCR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR1V : chan3FSR1V
    {60316, 452,  OFFSET(chan3FSR1V), "chan3FSR1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate1V : chan3Date1V
    {60318, 456,  OFFSET(chan3Date1V), "chan3Date1V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR10V : chan3OCR10V
    {60320, 460,  OFFSET(chan3OCR10V), "chan3OCR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR10V : chan3FSR10V
    {60322, 464,  OFFSET(chan3FSR10V), "chan3FSR10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate10V : chan3Date10V
    {60324, 468,  OFFSET(chan3Date10V), "chan3Date10V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR30V : chan3OCR30V
    {60326, 472,  OFFSET(chan3OCR30V), "chan3OCR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR30V : chan3FSR30V
    {60328, 476,  OFFSET(chan3FSR30V), "chan3FSR30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate30V : chan3Date30V
    {60330, 480,  OFFSET(chan3Date30V), "chan3Date30V", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR20mA : chan3OCR20mA
    {60332, 484,  OFFSET(chan3OCR20mA), "chan3OCR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFCR20mA : chan3FSR20mA
    {60334, 488,  OFFSET(chan3FSR20mA), "chan3FSR20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFDate20mA : chan3Date20mA
    {60336, 492,  OFFSET(chan3Date20mA), "chan3Date20mA", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR4x : chan3OCR4x
    {60338, 496,  OFFSET(chan3OCR4x), "chan3OCR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR4x : chan3FSR4x
    {60340, 500,  OFFSET(chan3FSR4x), "chan3FSR4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate4x : chan3Date4x
    {60342, 504,  OFFSET(chan3Date4x), "chan3Date4x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCR3x : chan3OCR3x
    {60344, 508,  OFFSET(chan3OCR3x), "chan3OCR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSR3x : chan3FSR3x
    {60346, 512,  OFFSET(chan3FSR3x), "chan3FSR3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDate3x : chan3Date3x
    {60348, 516,  OFFSET(chan3Date3x), "chan3Date3x", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibOCRinternal : chan3OCRinternal
    {60350, 520,  OFFSET(chan3OCRinternal), "chan3OCRinternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibFSRinternal : chan3FSRinternal
    {60352, 524,  OFFSET(chan3FSRinternal), "chan3FSRinternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
    // Parameter: CalibDateinternal : chan3DateInternal
    {60354, 528,  OFFSET(chan3DateInternal), "chan3DateInternal", LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_NA},
};
const uint16_t g_numLookupRegisters = (sizeof(g_stLookupRegisters)/sizeof(g_stLookupRegisters[0]));


