/************************************************************************************
 * Filename: lookup_tables.c
 *
 * Notice:
 *           THIS FILE AUTOMATICALLY GENERATED BY SPREADSHEET
 *                   ModbusMap.xlsm.
 *           MANUAL UPDATES TO THIS FILE WILL BE LOST.
 *
 *
***************************************************************************************
 *
 *
 *=====================================================================================
 * Description:
 *   C file for the Modbus registers and coil lookup tables. These tables map
 *   the registers/coils from Modbus to the appropriate location (I/O Processor or
 *   Sensor Processor). It also defines attributes such as type and protection.
 *
 * External Interface Functions:
 *   N/A
 *
 * Internal Functions:
 *   N/A
 *
***************************************************************************************/
#include <stdint.h>
//#include "cModbusController.h"
#include "lookupTables.h"
//
#define OFFSET(field) ( (uint16_t)offsetof(tDeviceBasicParams, field) )
//
// This is main storage for device parameters packed by 1 byte
#pragma pack(push, 1)
tDeviceBasicParams g_deviceDataStorage = {0};
#pragma pack(pop)

extern uint8_t mbRegRwCheckFunc(void* param, void* buffer);


// Register Map Definition
const tLookupRegisters g_stLookupRegisters[] =
{
    // {Par name, Par Offset, NV Offset, Check Func, Parameter Offset, Data Type, Data Size, Work Mode Access | Service Mode Access | Write Protect}
    // Parameter: Data channel 0
    {"DataChan0", 0, 0, mbRegRwCheckFunc,  OFFSET(DataChan0), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data channel 1
    {"DataChan1", 2, 0, mbRegRwCheckFunc,  OFFSET(DataChan1), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data channel 2
    {"DataChan2", 4, 0, mbRegRwCheckFunc,  OFFSET(DataChan2), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data channel 3
    {"DataChan3", 6, 0, mbRegRwCheckFunc,  OFFSET(DataChan3), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Protocol version
    {"protocolVersion", 16384, 0, mbRegRwCheckFunc,  OFFSET(protocolVersion), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Hardware version
    {"hardwareVersion", 16385, 2, mbRegRwCheckFunc,  OFFSET(hardwareVersion), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Software Version
    {"softwareVersion", 16386, 4, mbRegRwCheckFunc,  OFFSET(softwareVersion), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Software Revision
    {"softwareRevision", 16387, 6, mbRegRwCheckFunc,  OFFSET(softwareRevision), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Device Type
    {"deviceType", 16388, 8, mbRegRwCheckFunc,  OFFSET(deviceType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Modbus Network Address
    {"modbusAddress", 16389, 10, mbRegRwCheckFunc,  OFFSET(modbusAddress), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Modbus Baudrate
    {"modbusBaud", 16390, 10, mbRegRwCheckFunc,  OFFSET(modbusBaud), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Modbus parity
    {"modbusParity", 16391, 10, mbRegRwCheckFunc,  OFFSET(modbusParity), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Modbus stopbit
    {"mbStopBits", 16392, 10, mbRegRwCheckFunc,  OFFSET(mbStopBits), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Brace control
    {"mbBraceCtrl", 16393, 10, mbRegRwCheckFunc,  OFFSET(mbBraceCtrl), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Serial number
    {"serialNumber", 16395, 12, mbRegRwCheckFunc,  OFFSET(serialNumber), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Up time
    {"uptime", 16397, 16, mbRegRwCheckFunc,  OFFSET(uptime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Device state
    {"deviceState", 16399, 16, mbRegRwCheckFunc,  OFFSET(deviceState), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: DIP State
    {"disState", 16400, 16, mbRegRwCheckFunc,  OFFSET(disState), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Access type
    {"accessType", 16402, 16, mbRegRwCheckFunc,  OFFSET(accessType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data order
    {"dataOrder", 16403, 16, mbRegRwCheckFunc,  OFFSET(dataOrder), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Modbus comm count
    {"mbCommCount", 16404, 18, mbRegRwCheckFunc,  OFFSET(mbCommCount), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Modbus comm error
    {"mbCommError", 16405, 18, mbRegRwCheckFunc,  OFFSET(mbCommError), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Status
    {"deviceStatus", 16406, 18, mbRegRwCheckFunc,  OFFSET(deviceStatus), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Errors
    {"devErrors", 16407, 18, mbRegRwCheckFunc,  OFFSET(devErrors), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Factory date
    {"factoryDate", 16408, 18, mbRegRwCheckFunc,  OFFSET(factoryDate), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Software CRC32
    {"softwareCrc32", 16410, 22, mbRegRwCheckFunc,  OFFSET(softwareCrc32), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Unique ID
    {"uniqueId", 16412, 22, mbRegRwCheckFunc,  OFFSET(uniqueId), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_NA | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Root Access
    {"root_ Access", 16418, 26, mbRegRwCheckFunc,  OFFSET(root_Access), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_W | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: On-board temp
    {"onBoardTemp", 16419, 26, mbRegRwCheckFunc,  OFFSET(onBoardTemp), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: On-board voltage
    {"onBoardVoltage", 16421, 26, mbRegRwCheckFunc,  OFFSET(onBoardVoltage), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: AI count
    {"aiCount", 16423, 26, mbRegRwCheckFunc,  OFFSET(aiCount), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: DI count
    {"diCount", 16425, 26, mbRegRwCheckFunc,  OFFSET(diCount), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Model
    {"deviceModel", 16428, 26, mbRegRwCheckFunc,  OFFSET(deviceModel), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Data (Measure/Generate)
    {"chan0Data", 32768, 28, mbRegRwCheckFunc,  OFFSET(chan0Data), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data flags
    {"chan0DataFlags", 32770, 28, mbRegRwCheckFunc,  OFFSET(chan0DataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Status
    {"chan0Status", 32771, 28, mbRegRwCheckFunc,  OFFSET(chan0Status), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: ϸ颪衪ᮠ젮
    {"chan0Error", 32772, 28, mbRegRwCheckFunc,  OFFSET(chan0Error), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Quantity
    {"chan0Quantity", 32773, 28, mbRegRwCheckFunc,  OFFSET(chan0Quantity), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Uptime
    {"chan0Uptime", 32775, 28, mbRegRwCheckFunc,  OFFSET(chan0Uptime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data
    {"chan0RawData", 32777, 28, mbRegRwCheckFunc,  OFFSET(chan0RawData), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data flags
    {"chan0RawDataFlags", 32779, 28, mbRegRwCheckFunc,  OFFSET(chan0RawDataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Supported signals
    {"chan0SupportedSignals", 32780, 28, mbRegRwCheckFunc,  OFFSET(chan0SupportedSignals), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Signal Type
    {"chan0SignalType", 32781, 28, mbRegRwCheckFunc,  OFFSET(chan0SignalType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter1
    {"chan0AdditionalParameter1", 32782, 30, mbRegRwCheckFunc,  OFFSET(chan0AdditionalParameter1), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter2
    {"chan0AdditionalParameter2", 32788, 42, mbRegRwCheckFunc,  OFFSET(chan0AdditionalParameter2), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter type
    {"chan0FilterType", 32795, 54, mbRegRwCheckFunc,  OFFSET(chan0FilterType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter Length
    {"chan0FilterLength", 32796, 54, mbRegRwCheckFunc,  OFFSET(chan0FilterLength), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer Function
    {"chan0TransferFunction", 32797, 56, mbRegRwCheckFunc,  OFFSET(chan0TransferFunction), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal low limit
    {"chan0TransferSignalLowLim", 32799, 58, mbRegRwCheckFunc,  OFFSET(chan0TransferSignalLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal high limit
    {"chan0TransferSignalHighLim", 32801, 62, mbRegRwCheckFunc,  OFFSET(chan0TransferSignalHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale low limit
    {"chan0TransferScaleLowLim", 32803, 66, mbRegRwCheckFunc,  OFFSET(chan0TransferScaleLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale high limit
    {"chan0TransferScaleHighLim", 32805, 70, mbRegRwCheckFunc,  OFFSET(chan0TransferScaleHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Bad_Good_Comm
    {"chan0BadGoodComm", 32807, 74, mbRegRwCheckFunc,  OFFSET(chan0BadGoodComm), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Hi alarm_Reley
    {"chan0ReleyHi", 32810, 74, mbRegRwCheckFunc,  OFFSET(chan0ReleyHi), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Lo alarm_Reley
    {"chan0ReleyLo", 32811, 76, mbRegRwCheckFunc,  OFFSET(chan0ReleyLo), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Measured CJ Value
    {"chan0CjValue", 32856, 166, mbRegRwCheckFunc,  OFFSET(chan0CjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Result CJ Value
    {"chan0ResultCjValue", 32858, 166, mbRegRwCheckFunc,  OFFSET(chan0ResultCjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data (Measure/Generate)
    {"chan1Data", 32896, 166, mbRegRwCheckFunc,  OFFSET(chan1Data), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data flags
    {"chan1DataFlags", 32898, 166, mbRegRwCheckFunc,  OFFSET(chan1DataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Status
    {"chan1Status", 32899, 166, mbRegRwCheckFunc,  OFFSET(chan1Status), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: ϸ颪衪ᮠ젮
    {"chan1Error", 32900, 166, mbRegRwCheckFunc,  OFFSET(chan1Error), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Quantity
    {"chan1Quantity", 32901, 166, mbRegRwCheckFunc,  OFFSET(chan1Quantity), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Uptime
    {"chan1Uptime", 32903, 166, mbRegRwCheckFunc,  OFFSET(chan1Uptime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data
    {"chan1RawData", 32905, 166, mbRegRwCheckFunc,  OFFSET(chan1RawData), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data flags
    {"chan1RawDataFlags", 32907, 166, mbRegRwCheckFunc,  OFFSET(chan1RawDataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Supported signals
    {"chan1SupportedSignals", 32908, 166, mbRegRwCheckFunc,  OFFSET(chan1SupportedSignals), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Signal Type
    {"chan1SignalType", 32909, 166, mbRegRwCheckFunc,  OFFSET(chan1SignalType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter1
    {"chan1AdditionalParameter1", 32910, 168, mbRegRwCheckFunc,  OFFSET(chan1AdditionalParameter1), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter2
    {"chan1AdditionalParameter2", 32916, 180, mbRegRwCheckFunc,  OFFSET(chan1AdditionalParameter2), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter type
    {"chan1FilterType", 32923, 192, mbRegRwCheckFunc,  OFFSET(chan1FilterType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter Length
    {"chan1FilterLength", 32924, 192, mbRegRwCheckFunc,  OFFSET(chan1FilterLength), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer Function
    {"chan1TransferFunction", 32925, 194, mbRegRwCheckFunc,  OFFSET(chan1TransferFunction), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal low limit
    {"chan1TransferSignalLowLim", 32927, 196, mbRegRwCheckFunc,  OFFSET(chan1TransferSignalLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal high limit
    {"chan1TransferSignalHighLim", 32929, 200, mbRegRwCheckFunc,  OFFSET(chan1TransferSignalHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale low limit
    {"chan1TransferScaleLowLim", 32931, 204, mbRegRwCheckFunc,  OFFSET(chan1TransferScaleLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale high limit
    {"chan1TransferScaleHighLim", 32933, 208, mbRegRwCheckFunc,  OFFSET(chan1TransferScaleHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Bad_Good_Comm
    {"chan1BadGoodComm", 32935, 212, mbRegRwCheckFunc,  OFFSET(chan1BadGoodComm), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Hi alarm_Reley
    {"chan1ReleyHi", 32938, 212, mbRegRwCheckFunc,  OFFSET(chan1ReleyHi), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Lo alarm_Reley
    {"chan1ReleyLo", 32939, 214, mbRegRwCheckFunc,  OFFSET(chan1ReleyLo), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Measured CJ Value
    {"chan1CjValue", 32984, 304, mbRegRwCheckFunc,  OFFSET(chan1CjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Result CJ Value
    {"chan1ResultCjValue", 32986, 304, mbRegRwCheckFunc,  OFFSET(chan1ResultCjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data (Measure/Generate)
    {"chan2Data", 33024, 304, mbRegRwCheckFunc,  OFFSET(chan2Data), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data flags
    {"chan2DataFlags", 33026, 304, mbRegRwCheckFunc,  OFFSET(chan2DataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Status
    {"chan2Status", 33027, 304, mbRegRwCheckFunc,  OFFSET(chan2Status), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: ϸ颪衪ᮠ젮
    {"chan2Error", 33028, 304, mbRegRwCheckFunc,  OFFSET(chan2Error), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Quantity
    {"chan2Quantity", 33029, 304, mbRegRwCheckFunc,  OFFSET(chan2Quantity), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Uptime
    {"chan2Uptime", 33031, 304, mbRegRwCheckFunc,  OFFSET(chan2Uptime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data
    {"chan2RawData", 33033, 304, mbRegRwCheckFunc,  OFFSET(chan2RawData), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data flags
    {"chan2RawDataFlags", 33035, 304, mbRegRwCheckFunc,  OFFSET(chan2RawDataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Supported signals
    {"chan2SupportedSignals", 33036, 304, mbRegRwCheckFunc,  OFFSET(chan2SupportedSignals), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Signal Type
    {"chan2SignalType", 33037, 304, mbRegRwCheckFunc,  OFFSET(chan2SignalType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter1
    {"chan2AdditionalParameter1", 33038, 306, mbRegRwCheckFunc,  OFFSET(chan2AdditionalParameter1), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter2
    {"chan2AdditionalParameter2", 33044, 318, mbRegRwCheckFunc,  OFFSET(chan2AdditionalParameter2), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter type
    {"chan2FilterType", 33051, 330, mbRegRwCheckFunc,  OFFSET(chan2FilterType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter Length
    {"chan2FilterLength", 33052, 330, mbRegRwCheckFunc,  OFFSET(chan2FilterLength), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer Function
    {"chan2TransferFunction", 33053, 332, mbRegRwCheckFunc,  OFFSET(chan2TransferFunction), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal low limit
    {"chan2TransferSignalLowLim", 33055, 334, mbRegRwCheckFunc,  OFFSET(chan2TransferSignalLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal high limit
    {"chan2TransferSignalHighLim", 33057, 338, mbRegRwCheckFunc,  OFFSET(chan2TransferSignalHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale low limit
    {"chan2TransferScaleLowLim", 33059, 342, mbRegRwCheckFunc,  OFFSET(chan2TransferScaleLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale high limit
    {"chan2TransferScaleHighLim", 33061, 346, mbRegRwCheckFunc,  OFFSET(chan2TransferScaleHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Bad_Good_Comm
    {"chan2BadGoodComm", 33063, 350, mbRegRwCheckFunc,  OFFSET(chan2BadGoodComm), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Hi alarm_Reley
    {"chan2ReleyHi", 33066, 350, mbRegRwCheckFunc,  OFFSET(chan2ReleyHi), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Lo alarm_Reley
    {"chan2ReleyLo", 33067, 352, mbRegRwCheckFunc,  OFFSET(chan2ReleyLo), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Measured CJ Value
    {"chan2CjValue", 33112, 442, mbRegRwCheckFunc,  OFFSET(chan2CjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Result CJ Value
    {"chan2ResultCjValue", 33114, 442, mbRegRwCheckFunc,  OFFSET(chan2ResultCjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data (Measure/Generate)
    {"chan3Data", 33152, 442, mbRegRwCheckFunc,  OFFSET(chan3Data), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Data flags
    {"chan3DataFlags", 33154, 442, mbRegRwCheckFunc,  OFFSET(chan3DataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Status
    {"chan3Status", 33155, 442, mbRegRwCheckFunc,  OFFSET(chan3Status), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: ϸ颪衪ᮠ젮
    {"chan3Error", 33156, 442, mbRegRwCheckFunc,  OFFSET(chan3Error), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Quantity
    {"chan3Quantity", 33157, 442, mbRegRwCheckFunc,  OFFSET(chan3Quantity), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Uptime
    {"chan3Uptime", 33159, 442, mbRegRwCheckFunc,  OFFSET(chan3Uptime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data
    {"chan3RawData", 33161, 442, mbRegRwCheckFunc,  OFFSET(chan3RawData), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Raw Data flags
    {"chan3RawDataFlags", 33163, 442, mbRegRwCheckFunc,  OFFSET(chan3RawDataFlags), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Supported signals
    {"chan3SupportedSignals", 33164, 442, mbRegRwCheckFunc,  OFFSET(chan3SupportedSignals), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Signal Type
    {"chan3SignalType", 33165, 442, mbRegRwCheckFunc,  OFFSET(chan3SignalType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter1
    {"chan3AdditionalParameter1", 33166, 444, mbRegRwCheckFunc,  OFFSET(chan3AdditionalParameter1), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Additional parameter2
    {"chan3AdditionalParameter2", 33172, 456, mbRegRwCheckFunc,  OFFSET(chan3AdditionalParameter2), LKUP_TYPE_ASCII, 12, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter type
    {"chan3FilterType", 33179, 468, mbRegRwCheckFunc,  OFFSET(chan3FilterType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Filter Length
    {"chan3FilterLength", 33180, 468, mbRegRwCheckFunc,  OFFSET(chan3FilterLength), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer Function
    {"chan3TransferFunction", 33181, 470, mbRegRwCheckFunc,  OFFSET(chan3TransferFunction), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal low limit
    {"chan3TransferSignalLowLim", 33183, 472, mbRegRwCheckFunc,  OFFSET(chan3TransferSignalLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer signal high limit
    {"chan3TransferSignalHighLim", 33185, 476, mbRegRwCheckFunc,  OFFSET(chan3TransferSignalHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale low limit
    {"chan3TransferScaleLowLim", 33187, 480, mbRegRwCheckFunc,  OFFSET(chan3TransferScaleLowLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Transfer scale high limit
    {"chan3TransferScaleHighLim", 33189, 484, mbRegRwCheckFunc,  OFFSET(chan3TransferScaleHighLim), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Bad_Good_Comm
    {"chan3BadGoodComm", 33191, 488, mbRegRwCheckFunc,  OFFSET(chan3BadGoodComm), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Hi alarm_Reley
    {"chan3ReleyHi", 33194, 488, mbRegRwCheckFunc,  OFFSET(chan3ReleyHi), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Lo alarm_Reley
    {"chan3ReleyLo", 33195, 490, mbRegRwCheckFunc,  OFFSET(chan3ReleyLo), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
   // Parameter: Measured CJ Value
    {"chan3CjValue", 33240, 580, mbRegRwCheckFunc,  OFFSET(chan3CjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: Result CJ Value
    {"chan3ResultCjValue", 33242, 580, mbRegRwCheckFunc,  OFFSET(chan3ResultCjValue), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_WRITE_PROTECT},
    // Parameter: CalibOCR100mV
    {"chan0OCR100mV", 33244, 580, mbRegRwCheckFunc,  OFFSET(chan0OCR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR100mV
    {"chan0FSR100mV", 33246, 584, mbRegRwCheckFunc,  OFFSET(chan0FSR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate100mV
    {"chan0Date100mV", 33248, 588, mbRegRwCheckFunc,  OFFSET(chan0Date100mV), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR1V
    {"chan0OCR1V", 33250, 592, mbRegRwCheckFunc,  OFFSET(chan0OCR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR1V
    {"chan0FSR1V", 33252, 596, mbRegRwCheckFunc,  OFFSET(chan0FSR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate1V
    {"chan0Date1V", 33254, 600, mbRegRwCheckFunc,  OFFSET(chan0Date1V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR10V
    {"chan0OCR10V", 33256, 604, mbRegRwCheckFunc,  OFFSET(chan0OCR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR10V
    {"chan0FSR10V", 33258, 608, mbRegRwCheckFunc,  OFFSET(chan0FSR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate10V
    {"chan0Date10V", 33260, 612, mbRegRwCheckFunc,  OFFSET(chan0Date10V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR30V
    {"chan0OCR30V", 33262, 616, mbRegRwCheckFunc,  OFFSET(chan0OCR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR30V
    {"chan0FSR30V", 33264, 620, mbRegRwCheckFunc,  OFFSET(chan0FSR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate30V
    {"chan0Date30V", 33266, 624, mbRegRwCheckFunc,  OFFSET(chan0Date30V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR20mA
    {"chan0OCR20mA", 33268, 628, mbRegRwCheckFunc,  OFFSET(chan0OCR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR20mA
    {"chan0FSR20mA", 33270, 632, mbRegRwCheckFunc,  OFFSET(chan0FSR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate20mA
    {"chan0Date20mA", 33272, 636, mbRegRwCheckFunc,  OFFSET(chan0Date20mA), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR4x
    {"chan0OCR4x", 33274, 640, mbRegRwCheckFunc,  OFFSET(chan0OCR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR4x
    {"chan0FSR4x", 33276, 644, mbRegRwCheckFunc,  OFFSET(chan0FSR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate4x
    {"chan0Date4x", 33278, 648, mbRegRwCheckFunc,  OFFSET(chan0Date4x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR3x
    {"chan0OCR3x", 33280, 652, mbRegRwCheckFunc,  OFFSET(chan0OCR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR3x
    {"chan0FSR3x", 33282, 656, mbRegRwCheckFunc,  OFFSET(chan0FSR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate3x
    {"chan0Date3x", 33284, 660, mbRegRwCheckFunc,  OFFSET(chan0Date3x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCRinternal
    {"chan0OCRinternal", 33286, 664, mbRegRwCheckFunc,  OFFSET(chan0OCRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSRinternal
    {"chan0FSRinternal", 33288, 668, mbRegRwCheckFunc,  OFFSET(chan0FSRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDateinternal
    {"chan0DateRinternal", 33290, 672, mbRegRwCheckFunc,  OFFSET(chan0DateRinternal), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR100mV
    {"chan1OCR100mV", 33292, 676, mbRegRwCheckFunc,  OFFSET(chan1OCR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR100mV
    {"chan1FSR100mV", 33294, 680, mbRegRwCheckFunc,  OFFSET(chan1FSR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate100mV
    {"chan1Date100mV", 33296, 684, mbRegRwCheckFunc,  OFFSET(chan1Date100mV), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR1V
    {"chan1OCR1V", 33298, 688, mbRegRwCheckFunc,  OFFSET(chan1OCR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR1V
    {"chan1FSR1V", 33300, 692, mbRegRwCheckFunc,  OFFSET(chan1FSR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate1V
    {"chan1Date1V", 33302, 696, mbRegRwCheckFunc,  OFFSET(chan1Date1V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR10V
    {"chan1OCR10V", 33304, 700, mbRegRwCheckFunc,  OFFSET(chan1OCR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR10V
    {"chan1FSR10V", 33306, 704, mbRegRwCheckFunc,  OFFSET(chan1FSR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate10V
    {"chan1Date10V", 33308, 708, mbRegRwCheckFunc,  OFFSET(chan1Date10V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR30V
    {"chan1OCR30V", 33310, 712, mbRegRwCheckFunc,  OFFSET(chan1OCR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR30V
    {"chan1FSR30V", 33312, 716, mbRegRwCheckFunc,  OFFSET(chan1FSR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate30V
    {"chan1Date30V", 33314, 720, mbRegRwCheckFunc,  OFFSET(chan1Date30V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR20mA
    {"chan1OCR20mA", 33316, 724, mbRegRwCheckFunc,  OFFSET(chan1OCR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR20mA
    {"chan1FSR20mA", 33318, 728, mbRegRwCheckFunc,  OFFSET(chan1FSR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate20mA
    {"chan1Date20mA", 33320, 732, mbRegRwCheckFunc,  OFFSET(chan1Date20mA), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR4x
    {"chan1OCR4x", 33322, 736, mbRegRwCheckFunc,  OFFSET(chan1OCR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR4x
    {"chan1FSR4x", 33324, 740, mbRegRwCheckFunc,  OFFSET(chan1FSR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate4x
    {"chan1Date4x", 33326, 744, mbRegRwCheckFunc,  OFFSET(chan1Date4x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR3x
    {"chan1OCR3x", 33328, 748, mbRegRwCheckFunc,  OFFSET(chan1OCR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR3x
    {"chan1FSR3x", 33330, 752, mbRegRwCheckFunc,  OFFSET(chan1FSR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate3x
    {"chan1Date3x", 33332, 756, mbRegRwCheckFunc,  OFFSET(chan1Date3x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCRinternal
    {"chan1OCRinternal", 33334, 760, mbRegRwCheckFunc,  OFFSET(chan1OCRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSRinternal
    {"chan1FSRinternal", 33336, 764, mbRegRwCheckFunc,  OFFSET(chan1FSRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDateinternal
    {"chan1DateRinternal", 33338, 768, mbRegRwCheckFunc,  OFFSET(chan1DateRinternal), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR100mV
    {"chan2OCR100mV", 33340, 772, mbRegRwCheckFunc,  OFFSET(chan2OCR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR100mV
    {"chan2FSR100mV", 33342, 776, mbRegRwCheckFunc,  OFFSET(chan2FSR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate100mV
    {"chan2Date100mV", 33344, 780, mbRegRwCheckFunc,  OFFSET(chan2Date100mV), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR1V
    {"chan2OCR1V", 33346, 784, mbRegRwCheckFunc,  OFFSET(chan2OCR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR1V
    {"chan2FSR1V", 33348, 788, mbRegRwCheckFunc,  OFFSET(chan2FSR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate1V
    {"chan2Date1V", 33350, 792, mbRegRwCheckFunc,  OFFSET(chan2Date1V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR10V
    {"chan2OCR10V", 33352, 796, mbRegRwCheckFunc,  OFFSET(chan2OCR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR10V
    {"chan2FSR10V", 33354, 800, mbRegRwCheckFunc,  OFFSET(chan2FSR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate10V
    {"chan2Date10V", 33356, 804, mbRegRwCheckFunc,  OFFSET(chan2Date10V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR30V
    {"chan2OCR30V", 33358, 808, mbRegRwCheckFunc,  OFFSET(chan2OCR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR30V
    {"chan2FSR30V", 33360, 812, mbRegRwCheckFunc,  OFFSET(chan2FSR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate30V
    {"chan2Date30V", 33362, 816, mbRegRwCheckFunc,  OFFSET(chan2Date30V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR20mA
    {"chan2OCR20mA", 33364, 820, mbRegRwCheckFunc,  OFFSET(chan2OCR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR20mA
    {"chan2FSR20mA", 33366, 824, mbRegRwCheckFunc,  OFFSET(chan2FSR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate20mA
    {"chan2Date20mA", 33368, 828, mbRegRwCheckFunc,  OFFSET(chan2Date20mA), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR4x
    {"chan2OCR4x", 33370, 832, mbRegRwCheckFunc,  OFFSET(chan2OCR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR4x
    {"chan2FSR4x", 33372, 836, mbRegRwCheckFunc,  OFFSET(chan2FSR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate4x
    {"chan2Date4x", 33374, 840, mbRegRwCheckFunc,  OFFSET(chan2Date4x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR3x
    {"chan2OCR3x", 33376, 844, mbRegRwCheckFunc,  OFFSET(chan2OCR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR3x
    {"chan2FSR3x", 33378, 848, mbRegRwCheckFunc,  OFFSET(chan2FSR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate3x
    {"chan2Date3x", 33380, 852, mbRegRwCheckFunc,  OFFSET(chan2Date3x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCRinternal
    {"chan2OCRinternal", 33382, 856, mbRegRwCheckFunc,  OFFSET(chan2OCRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSRinternal
    {"chan2FSRinternal", 33384, 860, mbRegRwCheckFunc,  OFFSET(chan2FSRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDateinternal
    {"chan2DateRinternal", 33386, 864, mbRegRwCheckFunc,  OFFSET(chan2DateRinternal), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR100mV
    {"chan3OCR100mV", 33388, 868, mbRegRwCheckFunc,  OFFSET(chan3OCR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR100mV
    {"chan3FSR100mV", 33390, 872, mbRegRwCheckFunc,  OFFSET(chan3FSR100mV), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate100mV
    {"chan3Date100mV", 33392, 876, mbRegRwCheckFunc,  OFFSET(chan3Date100mV), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR1V
    {"chan3OCR1V", 33394, 880, mbRegRwCheckFunc,  OFFSET(chan3OCR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR1V
    {"chan3FSR1V", 33396, 884, mbRegRwCheckFunc,  OFFSET(chan3FSR1V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate1V
    {"chan3Date1V", 33398, 888, mbRegRwCheckFunc,  OFFSET(chan3Date1V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR10V
    {"chan3OCR10V", 33400, 892, mbRegRwCheckFunc,  OFFSET(chan3OCR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR10V
    {"chan3FSR10V", 33402, 896, mbRegRwCheckFunc,  OFFSET(chan3FSR10V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate10V
    {"chan3Date10V", 33404, 900, mbRegRwCheckFunc,  OFFSET(chan3Date10V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR30V
    {"chan3OCR30V", 33406, 904, mbRegRwCheckFunc,  OFFSET(chan3OCR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR30V
    {"chan3FSR30V", 33408, 908, mbRegRwCheckFunc,  OFFSET(chan3FSR30V), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate30V
    {"chan3Date30V", 33410, 912, mbRegRwCheckFunc,  OFFSET(chan3Date30V), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR20mA
    {"chan3OCR20mA", 33412, 916, mbRegRwCheckFunc,  OFFSET(chan3OCR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFCR20mA
    {"chan3FSR20mA", 33414, 920, mbRegRwCheckFunc,  OFFSET(chan3FSR20mA), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFDate20mA
    {"chan3Date20mA", 33416, 924, mbRegRwCheckFunc,  OFFSET(chan3Date20mA), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR4x
    {"chan3OCR4x", 33418, 928, mbRegRwCheckFunc,  OFFSET(chan3OCR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR4x
    {"chan3FSR4x", 33420, 932, mbRegRwCheckFunc,  OFFSET(chan3FSR4x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate4x
    {"chan3Date4x", 33422, 936, mbRegRwCheckFunc,  OFFSET(chan3Date4x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCR3x
    {"chan3OCR3x", 33424, 940, mbRegRwCheckFunc,  OFFSET(chan3OCR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSR3x
    {"chan3FSR3x", 33426, 944, mbRegRwCheckFunc,  OFFSET(chan3FSR3x), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDate3x
    {"chan3Date3x", 33428, 948, mbRegRwCheckFunc,  OFFSET(chan3Date3x), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibOCRinternal
    {"chan3OCRinternal", 33430, 952, mbRegRwCheckFunc,  OFFSET(chan3OCRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibFSRinternal
    {"chan3FSRinternal", 33432, 956, mbRegRwCheckFunc,  OFFSET(chan3FSRinternal), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: CalibDateinternal
    {"chan3DateRinternal", 33434, 960, mbRegRwCheckFunc,  OFFSET(chan3DateRinternal), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Digital Data
    {"chan0DIData", 33436, 964, mbRegRwCheckFunc,  OFFSET(chan0DIData), LKUP_TYPE_FLOAT, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Number of pulses
    {"chan0DIPulse", 33438, 964, mbRegRwCheckFunc,  OFFSET(chan0DIPulse), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_DYNAMIC | LKUP_ACCESS_WORK_R | LKUP_ACCESS_SERV_R | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Time pulses
    {"chan0DITime", 33440, 964, mbRegRwCheckFunc,  OFFSET(chan0DITime), LKUP_TYPE_U32, 4, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
    // Parameter: Signal Type(DI)
    {"chan0DISignalType", 33442, 968, mbRegRwCheckFunc,  OFFSET(chan0DISignalType), LKUP_TYPE_U16, 2, LKUP_ACCESS_TYPE_STATIC | LKUP_ACCESS_WORK_RW | LKUP_ACCESS_SERV_RW | LKUP_ACCESS_NO_WRITE_PROTECT},
};
const uint16_t g_numLookupRegisters = (sizeof(g_stLookupRegisters)/sizeof(g_stLookupRegisters[0]));


