/************************************************************************************
 * Filename: device_params.h
 *
 * Notice:
 *           THIS FILE AUTOMATICALLY GENERATED BY SPREADSHEET
 *                   ExtModbus.xlsm. 
 *           MANUAL UPDATES TO THIS FILE WILL BE LOST.
 *
 *
***************************************************************************************
 *
 *
 *=====================================================================================
 * Description:
 *   Header file for the Modbus registers and coil lookup tables. These tables map
 *   the registers/coils from Modbus to the appropriate location (I/O Processor or
 *   Sensor Processor). It also defines attributes such as type and protection.
 *
 * External Interface Functions:
 *   N/A
 *
 * Internal Functions:
 *   N/A
 * 
***************************************************************************************/
 
#ifndef DEVICE_PARAMS_H
#define DEVICE_PARAMS_H
 
#include <stdint.h>
#define GET_PARAM_ADDRESS(parInfo) ( (uint8_t*)((uint8_t*)&g_extModbusDataStorage + parInfo->paramOffset)  )
 
#define A12_ARR_SIZE 12
 
#pragma pack(push, 1)
// Register Structure Definition
typedef struct
{
    // Parameter: Relay 1  : relay1 : MB Offset: 0
    uint8_t relay1;
    // Parameter: Relay 2 : relay2 : MB Offset: 1
    uint8_t relay2;
    // Parameter: Relay 3 : relay3 : MB Offset: 2
    uint8_t relay3;
    // Parameter: Relay 4 : relay4 : MB Offset: 3
    uint8_t relay4;
    // Parameter: Relay 5 : relay5 : MB Offset: 4
    uint8_t relay5;
    // Parameter: Relay 6 : relay6 : MB Offset: 5
    uint8_t relay6;
    // Parameter: Relay 7 : relay7 : MB Offset: 6
    uint8_t relay7;
    // Parameter: Relay 8 : relay8 : MB Offset: 7
    uint8_t relay8;
    // Parameter: Relay 9 : relay9 : MB Offset: 8
    uint8_t relay9;
    // Parameter: Relay 10 : relay10 : MB Offset: 9
    uint8_t relay10;
    // Parameter: Relay 11 : relay11 : MB Offset: 10
    uint8_t relay11;
    // Parameter: Relay 12 : relay12 : MB Offset: 11
    uint8_t relay12;
    // Parameter: Relay 13 : relay13 : MB Offset: 12
    uint8_t relay13;
    // Parameter: Relay 14 : relay14 : MB Offset: 13
    uint8_t relay14;
    // Parameter: Relay 15 : relay15 : MB Offset: 14
    uint8_t relay15;
    // Parameter: Relay 16 : relay16 : MB Offset: 15
    uint8_t relay16;
    // Parameter: Relay 17 : relay17 : MB Offset: 16
    uint8_t relay17;
    // Parameter: Relay 18 : relay18 : MB Offset: 17
    uint8_t relay18;
    // Parameter: Relay 19 : relay19 : MB Offset: 18
    uint8_t relay19;
    // Parameter: Relay 20 : relay20 : MB Offset: 19
    uint8_t relay20;
    // Parameter: Relay 21 : relay21 : MB Offset: 20
    uint8_t relay21;
    // Parameter: Relay 22 : relay22 : MB Offset: 21
    uint8_t relay22;
    // Parameter: Relay 23 : relay23 : MB Offset: 22
    uint8_t relay23;
    // Parameter: Relay 24 : relay24 : MB Offset: 23
    uint8_t relay24;
    // Parameter: Relay 25 : relay25 : MB Offset: 24
    uint8_t relay25;
    // Parameter: Relay 26 : relay26 : MB Offset: 25
    uint8_t relay26;
    // Parameter: Relay 27 : relay27 : MB Offset: 26
    uint8_t relay27;
    // Parameter: Relay 28 : relay28 : MB Offset: 27
    uint8_t relay28;
    // Parameter: Relay 29 : relay29 : MB Offset: 28
    uint8_t relay29;
    // Parameter: Relay 30 : relay30 : MB Offset: 29
    uint8_t relay30;
    // Parameter: Relay 31 : relay31 : MB Offset: 30
    uint8_t relay31;
    // Parameter: Relay 32 : relay32 : MB Offset: 31
    uint8_t relay32;
    // Parameter: Ustavka 1  : ustavka1 : MB Offset: 0
    uint8_t ustavka1;
    // Parameter: Ustavka 2 : ustavka2 : MB Offset: 1
    uint8_t ustavka2;
    // Parameter: Ustavka 3 : ustavka3 : MB Offset: 2
    uint8_t ustavka3;
    // Parameter: Ustavka 4 : ustavka4 : MB Offset: 3
    uint8_t ustavka4;
    // Parameter: Ustavka 5 : ustavka5 : MB Offset: 4
    uint8_t ustavka5;
    // Parameter: Ustavka 6 : ustavka6 : MB Offset: 5
    uint8_t ustavka6;
    // Parameter: Ustavka 7 : ustavka7 : MB Offset: 6
    uint8_t ustavka7;
    // Parameter: Ustavka 8 : ustavka8 : MB Offset: 7
    uint8_t ustavka8;
    // Parameter: Ustavka 9 : ustavka9 : MB Offset: 8
    uint8_t ustavka9;
    // Parameter: Ustavka 10 : ustavka10 : MB Offset: 9
    uint8_t ustavka10;
    // Parameter: Ustavka 11 : ustavka11 : MB Offset: 10
    uint8_t ustavka11;
    // Parameter: Ustavka 12 : ustavka12 : MB Offset: 11
    uint8_t ustavka12;
    // Parameter: Ustavka 13 : ustavka13 : MB Offset: 12
    uint8_t ustavka13;
    // Parameter: Ustavka 14 : ustavka14 : MB Offset: 13
    uint8_t ustavka14;
    // Parameter: Ustavka 15 : ustavka15 : MB Offset: 14
    uint8_t ustavka15;
    // Parameter: Ustavka 16 : ustavka16 : MB Offset: 15
    uint8_t ustavka16;
    // Parameter: Ustavka 17 : ustavka17 : MB Offset: 16
    uint8_t ustavka17;
    // Parameter: Ustavka 18 : ustavka18 : MB Offset: 17
    uint8_t ustavka18;
    // Parameter: Ustavka 19 : ustavka19 : MB Offset: 18
    uint8_t ustavka19;
    // Parameter: Ustavka 20 : ustavka20 : MB Offset: 19
    uint8_t ustavka20;
    // Parameter: Ustavka 21 : ustavka21 : MB Offset: 20
    uint8_t ustavka21;
    // Parameter: Ustavka 22 : ustavka22 : MB Offset: 21
    uint8_t ustavka22;
    // Parameter: Ustavka 23 : ustavka23 : MB Offset: 22
    uint8_t ustavka23;
    // Parameter: Ustavka 24 : ustavka24 : MB Offset: 23
    uint8_t ustavka24;
    // Parameter: Ustavka 25 : ustavka25 : MB Offset: 24
    uint8_t ustavka25;
    // Parameter: Ustavka 26 : ustavka26 : MB Offset: 25
    uint8_t ustavka26;
    // Parameter: Ustavka 27 : ustavka27 : MB Offset: 26
    uint8_t ustavka27;
    // Parameter: Ustavka 28 : ustavka28 : MB Offset: 27
    uint8_t ustavka28;
    // Parameter: Ustavka 29 : ustavka29 : MB Offset: 28
    uint8_t ustavka29;
    // Parameter: Ustavka 30 : ustavka30 : MB Offset: 29
    uint8_t ustavka30;
    // Parameter: Ustavka 31 : ustavka31 : MB Offset: 30
    uint8_t ustavka31;
    // Parameter: Ustavka 32 : ustavka32 : MB Offset: 31
    uint8_t ustavka32;
    // Parameter: Ustavka 33 : ustavka33 : MB Offset: 32
    uint8_t ustavka33;
    // Parameter: Ustavka 34 : ustavka34 : MB Offset: 33
    uint8_t ustavka34;
    // Parameter: Ustavka 35 : ustavka35 : MB Offset: 34
    uint8_t ustavka35;
    // Parameter: Ustavka 36 : ustavka36 : MB Offset: 35
    uint8_t ustavka36;
    // Parameter: Ustavka 37 : ustavka37 : MB Offset: 36
    uint8_t ustavka37;
    // Parameter: Ustavka 38 : ustavka38 : MB Offset: 37
    uint8_t ustavka38;
    // Parameter: Ustavka 39 : ustavka39 : MB Offset: 38
    uint8_t ustavka39;
    // Parameter: Ustavka 40 : ustavka40 : MB Offset: 39
    uint8_t ustavka40;
    // Parameter: Ustavka 41 : ustavka41 : MB Offset: 40
    uint8_t ustavka41;
    // Parameter: Ustavka 42 : ustavka42 : MB Offset: 41
    uint8_t ustavka42;
    // Parameter: Ustavka 43 : ustavka43 : MB Offset: 42
    uint8_t ustavka43;
    // Parameter: Ustavka 44 : ustavka44 : MB Offset: 43
    uint8_t ustavka44;
    // Parameter: Ustavka 45 : ustavka45 : MB Offset: 44
    uint8_t ustavka45;
    // Parameter: Ustavka 46 : ustavka46 : MB Offset: 45
    uint8_t ustavka46;
    // Parameter: Ustavka 47 : ustavka47 : MB Offset: 46
    uint8_t ustavka47;
    // Parameter: Ustavka 48 : ustavka48 : MB Offset: 47
    uint8_t ustavka48;
    // Parameter: Ustavka 49 : ustavka49 : MB Offset: 48
    uint8_t ustavka49;
    // Parameter: Ustavka 50 : ustavka50 : MB Offset: 49
    uint8_t ustavka50;
    // Parameter: Ustavka 51 : ustavka51 : MB Offset: 50
    uint8_t ustavka51;
    // Parameter: Ustavka 52 : ustavka52 : MB Offset: 51
    uint8_t ustavka52;
    // Parameter: Ustavka 53 : ustavka53 : MB Offset: 52
    uint8_t ustavka53;
    // Parameter: Ustavka 54 : ustavka54 : MB Offset: 53
    uint8_t ustavka54;
    // Parameter: Ustavka 55 : ustavka55 : MB Offset: 54
    uint8_t ustavka55;
    // Parameter: Ustavka 56 : ustavka56 : MB Offset: 55
    uint8_t ustavka56;
    // Parameter: Ustavka 57 : ustavka57 : MB Offset: 56
    uint8_t ustavka57;
    // Parameter: Ustavka 58 : ustavka58 : MB Offset: 57
    uint8_t ustavka58;
    // Parameter: Ustavka 59 : ustavka59 : MB Offset: 58
    uint8_t ustavka59;
    // Parameter: Ustavka 60 : ustavka60 : MB Offset: 59
    uint8_t ustavka60;
    // Parameter: Ustavka 61 : ustavka61 : MB Offset: 60
    uint8_t ustavka61;
    // Parameter: Ustavka 62 : ustavka62 : MB Offset: 61
    uint8_t ustavka62;
    // Parameter: Ustavka 63 : ustavka63 : MB Offset: 62
    uint8_t ustavka63;
    // Parameter: Ustavka 64 : ustavka64 : MB Offset: 63
    uint8_t ustavka64;
    // Parameter: Ustavka 65 : ustavka65 : MB Offset: 64
    uint8_t ustavka65;
    // Parameter: Ustavka 66 : ustavka66 : MB Offset: 65
    uint8_t ustavka66;
    // Parameter: Ustavka 67 : ustavka67 : MB Offset: 66
    uint8_t ustavka67;
    // Parameter: Ustavka 68 : ustavka68 : MB Offset: 67
    uint8_t ustavka68;
    // Parameter: Ustavka 69 : ustavka69 : MB Offset: 68
    uint8_t ustavka69;
    // Parameter: Ustavka 70 : ustavka70 : MB Offset: 69
    uint8_t ustavka70;
    // Parameter: Ustavka 71 : ustavka71 : MB Offset: 70
    uint8_t ustavka71;
    // Parameter: Ustavka 72 : ustavka72 : MB Offset: 71
    uint8_t ustavka72;
    // Parameter: Ustavka 73 : ustavka73 : MB Offset: 72
    uint8_t ustavka73;
    // Parameter: Ustavka 74 : ustavka74 : MB Offset: 73
    uint8_t ustavka74;
    // Parameter: Ustavka 75 : ustavka75 : MB Offset: 74
    uint8_t ustavka75;
    // Parameter: Ustavka 76 : ustavka76 : MB Offset: 75
    uint8_t ustavka76;
    // Parameter: Ustavka 77 : ustavka77 : MB Offset: 76
    uint8_t ustavka77;
    // Parameter: Ustavka 78 : ustavka78 : MB Offset: 77
    uint8_t ustavka78;
    // Parameter: Ustavka 79 : ustavka79 : MB Offset: 78
    uint8_t ustavka79;
    // Parameter: Ustavka 80 : ustavka80 : MB Offset: 79
    uint8_t ustavka80;
    // Parameter: Ustavka 81 : ustavka81 : MB Offset: 80
    uint8_t ustavka81;
    // Parameter: Ustavka 82 : ustavka82 : MB Offset: 81
    uint8_t ustavka82;
    // Parameter: Ustavka 83 : ustavka83 : MB Offset: 82
    uint8_t ustavka83;
    // Parameter: Ustavka 84 : ustavka84 : MB Offset: 83
    uint8_t ustavka84;
    // Parameter: Ustavka 85 : ustavka85 : MB Offset: 84
    uint8_t ustavka85;
    // Parameter: Ustavka 86 : ustavka86 : MB Offset: 85
    uint8_t ustavka86;
    // Parameter: Ustavka 87 : ustavka87 : MB Offset: 86
    uint8_t ustavka87;
    // Parameter: Ustavka 88 : ustavka88 : MB Offset: 87
    uint8_t ustavka88;
    // Parameter: Ustavka 89 : ustavka89 : MB Offset: 88
    uint8_t ustavka89;
    // Parameter: Ustavka 90 : ustavka90 : MB Offset: 89
    uint8_t ustavka90;
    // Parameter: Ustavka 91 : ustavka91 : MB Offset: 90
    uint8_t ustavka91;
    // Parameter: Ustavka 92 : ustavka92 : MB Offset: 91
    uint8_t ustavka92;
    // Parameter: Ustavka 93 : ustavka93 : MB Offset: 92
    uint8_t ustavka93;
    // Parameter: Ustavka 94 : ustavka94 : MB Offset: 93
    uint8_t ustavka94;
    // Parameter: Ustavka 95 : ustavka95 : MB Offset: 94
    uint8_t ustavka95;
    // Parameter: Ustavka 96 : ustavka96 : MB Offset: 95
    uint8_t ustavka96;
    // Parameter: Ustavka 97 : ustavka97 : MB Offset: 96
    uint8_t ustavka97;
    // Parameter: Ustavka 98 : ustavka98 : MB Offset: 97
    uint8_t ustavka98;
    // Parameter: Ustavka 99 : ustavka99 : MB Offset: 98
    uint8_t ustavka99;
    // Parameter: Ustavka 100 : ustavka100 : MB Offset: 99
    uint8_t ustavka100;
    // Parameter: Ustavka 101 : ustavka101 : MB Offset: 100
    uint8_t ustavka101;
    // Parameter: Ustavka 102 : ustavka102 : MB Offset: 101
    uint8_t ustavka102;
    // Parameter: Ustavka 103 : ustavka103 : MB Offset: 102
    uint8_t ustavka103;
    // Parameter: Ustavka 104 : ustavka104 : MB Offset: 103
    uint8_t ustavka104;
    // Parameter: Ustavka 105 : ustavka105 : MB Offset: 104
    uint8_t ustavka105;
    // Parameter: Ustavka 106 : ustavka106 : MB Offset: 105
    uint8_t ustavka106;
    // Parameter: Ustavka 107 : ustavka107 : MB Offset: 106
    uint8_t ustavka107;
    // Parameter: Ustavka 108 : ustavka108 : MB Offset: 107
    uint8_t ustavka108;
    // Parameter: Ustavka 109 : ustavka109 : MB Offset: 108
    uint8_t ustavka109;
    // Parameter: Ustavka 110 : ustavka110 : MB Offset: 109
    uint8_t ustavka110;
    // Parameter: Ustavka 111 : ustavka111 : MB Offset: 110
    uint8_t ustavka111;
    // Parameter: Ustavka 112 : ustavka112 : MB Offset: 111
    uint8_t ustavka112;
    // Parameter: Ustavka 113 : ustavka113 : MB Offset: 112
    uint8_t ustavka113;
    // Parameter: Ustavka 114 : ustavka114 : MB Offset: 113
    uint8_t ustavka114;
    // Parameter: Ustavka 115 : ustavka115 : MB Offset: 114
    uint8_t ustavka115;
    // Parameter: Ustavka 116 : ustavka116 : MB Offset: 115
    uint8_t ustavka116;
    // Parameter: Ustavka 117 : ustavka117 : MB Offset: 116
    uint8_t ustavka117;
    // Parameter: Ustavka 118 : ustavka118 : MB Offset: 117
    uint8_t ustavka118;
    // Parameter: Ustavka 119 : ustavka119 : MB Offset: 118
    uint8_t ustavka119;
    // Parameter: Ustavka 120 : ustavka120 : MB Offset: 119
    uint8_t ustavka120;
    // Parameter: Ustavka 121 : ustavka121 : MB Offset: 120
    uint8_t ustavka121;
    // Parameter: Ustavka 122 : ustavka122 : MB Offset: 121
    uint8_t ustavka122;
    // Parameter: Ustavka 123 : ustavka123 : MB Offset: 122
    uint8_t ustavka123;
    // Parameter: Ustavka 124 : ustavka124 : MB Offset: 123
    uint8_t ustavka124;
    // Parameter: Ustavka 125 : ustavka125 : MB Offset: 124
    uint8_t ustavka125;
    // Parameter: Ustavka 126 : ustavka126 : MB Offset: 125
    uint8_t ustavka126;
    // Parameter: Ustavka 127 : ustavka127 : MB Offset: 126
    uint8_t ustavka127;
    // Parameter: Ustavka 128 : ustavka128 : MB Offset: 127
    uint8_t ustavka128;
    // Parameter: Ustavka 129 : ustavka129 : MB Offset: 128
    uint8_t ustavka129;
    // Parameter: Ustavka 130 : ustavka130 : MB Offset: 129
    uint8_t ustavka130;
    // Parameter: Ustavka 131 : ustavka131 : MB Offset: 130
    uint8_t ustavka131;
    // Parameter: Ustavka 132 : ustavka132 : MB Offset: 131
    uint8_t ustavka132;
    // Parameter: Ustavka 133 : ustavka133 : MB Offset: 132
    uint8_t ustavka133;
    // Parameter: Ustavka 134 : ustavka134 : MB Offset: 133
    uint8_t ustavka134;
    // Parameter: Ustavka 135 : ustavka135 : MB Offset: 134
    uint8_t ustavka135;
    // Parameter: Ustavka 136 : ustavka136 : MB Offset: 135
    uint8_t ustavka136;
    // Parameter: Ustavka 137 : ustavka137 : MB Offset: 136
    uint8_t ustavka137;
    // Parameter: Ustavka 138 : ustavka138 : MB Offset: 137
    uint8_t ustavka138;
    // Parameter: Ustavka 139 : ustavka139 : MB Offset: 138
    uint8_t ustavka139;
    // Parameter: Ustavka 140 : ustavka140 : MB Offset: 139
    uint8_t ustavka140;
    // Parameter: Ustavka 141 : ustavka141 : MB Offset: 140
    uint8_t ustavka141;
    // Parameter: Ustavka 142 : ustavka142 : MB Offset: 141
    uint8_t ustavka142;
    // Parameter: Ustavka 143 : ustavka143 : MB Offset: 142
    uint8_t ustavka143;
    // Parameter: Ustavka 144 : ustavka144 : MB Offset: 143
    uint8_t ustavka144;
    // Parameter: Ustavka 145 : ustavka145 : MB Offset: 144
    uint8_t ustavka145;
    // Parameter: Ustavka 146 : ustavka146 : MB Offset: 145
    uint8_t ustavka146;
    // Parameter: Ustavka 147 : ustavka147 : MB Offset: 146
    uint8_t ustavka147;
    // Parameter: Ustavka 148 : ustavka148 : MB Offset: 147
    uint8_t ustavka148;
    // Parameter: Ustavka 149 : ustavka149 : MB Offset: 148
    uint8_t ustavka149;
    // Parameter: Ustavka 150 : ustavka150 : MB Offset: 149
    uint8_t ustavka150;
    // Parameter: Ustavka 151 : ustavka151 : MB Offset: 150
    uint8_t ustavka151;
    // Parameter: Ustavka 152 : ustavka152 : MB Offset: 151
    uint8_t ustavka152;
    // Parameter: Ustavka 153 : ustavka153 : MB Offset: 152
    uint8_t ustavka153;
    // Parameter: Ustavka 154 : ustavka154 : MB Offset: 153
    uint8_t ustavka154;
    // Parameter: Ustavka 155 : ustavka155 : MB Offset: 154
    uint8_t ustavka155;
    // Parameter: Ustavka 156 : ustavka156 : MB Offset: 155
    uint8_t ustavka156;
    // Parameter: Ustavka 157 : ustavka157 : MB Offset: 156
    uint8_t ustavka157;
    // Parameter: Ustavka 158 : ustavka158 : MB Offset: 157
    uint8_t ustavka158;
    // Parameter: Ustavka 159 : ustavka159 : MB Offset: 158
    uint8_t ustavka159;
    // Parameter: Ustavka 160 : ustavka160 : MB Offset: 159
    uint8_t ustavka160;
    // Parameter: Ustavka 161 : ustavka161 : MB Offset: 160
    uint8_t ustavka161;
    // Parameter: Ustavka 162 : ustavka162 : MB Offset: 161
    uint8_t ustavka162;
    // Parameter: Ustavka 163 : ustavka163 : MB Offset: 162
    uint8_t ustavka163;
    // Parameter: Ustavka 164 : ustavka164 : MB Offset: 163
    uint8_t ustavka164;
    // Parameter: Ustavka 165 : ustavka165 : MB Offset: 164
    uint8_t ustavka165;
    // Parameter: Ustavka 166 : ustavka166 : MB Offset: 165
    uint8_t ustavka166;
    // Parameter: Ustavka 167 : ustavka167 : MB Offset: 166
    uint8_t ustavka167;
    // Parameter: Ustavka 168 : ustavka168 : MB Offset: 167
    uint8_t ustavka168;
    // Parameter: Ustavka 169 : ustavka169 : MB Offset: 168
    uint8_t ustavka169;
    // Parameter: Ustavka 170 : ustavka170 : MB Offset: 169
    uint8_t ustavka170;
    // Parameter: Ustavka 171 : ustavka171 : MB Offset: 170
    uint8_t ustavka171;
    // Parameter: Ustavka 172 : ustavka172 : MB Offset: 171
    uint8_t ustavka172;
    // Parameter: Ustavka 173 : ustavka173 : MB Offset: 172
    uint8_t ustavka173;
    // Parameter: Ustavka 174 : ustavka174 : MB Offset: 173
    uint8_t ustavka174;
    // Parameter: Ustavka 175 : ustavka175 : MB Offset: 174
    uint8_t ustavka175;
    // Parameter: Ustavka 176 : ustavka176 : MB Offset: 175
    uint8_t ustavka176;
    // Parameter: Ustavka 177 : ustavka177 : MB Offset: 176
    uint8_t ustavka177;
    // Parameter: Ustavka 178 : ustavka178 : MB Offset: 177
    uint8_t ustavka178;
    // Parameter: Ustavka 179 : ustavka179 : MB Offset: 178
    uint8_t ustavka179;
    // Parameter: Ustavka 180 : ustavka180 : MB Offset: 179
    uint8_t ustavka180;
    // Parameter: Ustavka 181 : ustavka181 : MB Offset: 180
    uint8_t ustavka181;
    // Parameter: Ustavka 182 : ustavka182 : MB Offset: 181
    uint8_t ustavka182;
    // Parameter: Ustavka 183 : ustavka183 : MB Offset: 182
    uint8_t ustavka183;
    // Parameter: Ustavka 184 : ustavka184 : MB Offset: 183
    uint8_t ustavka184;
    // Parameter: Ustavka 185 : ustavka185 : MB Offset: 184
    uint8_t ustavka185;
    // Parameter: Ustavka 186 : ustavka186 : MB Offset: 185
    uint8_t ustavka186;
    // Parameter: Ustavka 187 : ustavka187 : MB Offset: 186
    uint8_t ustavka187;
    // Parameter: Ustavka 188 : ustavka188 : MB Offset: 187
    uint8_t ustavka188;
    // Parameter: Ustavka 189 : ustavka189 : MB Offset: 188
    uint8_t ustavka189;
    // Parameter: Ustavka 190 : ustavka190 : MB Offset: 189
    uint8_t ustavka190;
    // Parameter: Ustavka 191 : ustavka191 : MB Offset: 190
    uint8_t ustavka191;
    // Parameter: Ustavka 192 : ustavka192 : MB Offset: 191
    uint8_t ustavka192;
    // Parameter: Ustavka 193 : ustavka193 : MB Offset: 192
    uint8_t ustavka193;
    // Parameter: Ustavka 194 : ustavka194 : MB Offset: 193
    uint8_t ustavka194;
    // Parameter: Ustavka 195 : ustavka195 : MB Offset: 194
    uint8_t ustavka195;
    // Parameter: Ustavka 196 : ustavka196 : MB Offset: 195
    uint8_t ustavka196;
    // Parameter: Ustavka 197 : ustavka197 : MB Offset: 196
    uint8_t ustavka197;
    // Parameter: Ustavka 198 : ustavka198 : MB Offset: 197
    uint8_t ustavka198;
    // Parameter: Ustavka 199 : ustavka199 : MB Offset: 198
    uint8_t ustavka199;
    // Parameter: Ustavka 200 : ustavka200 : MB Offset: 199
    uint8_t ustavka200;
    // Parameter: Ustavka 201 : ustavka201 : MB Offset: 200
    uint8_t ustavka201;
    // Parameter: Ustavka 202 : ustavka202 : MB Offset: 201
    uint8_t ustavka202;
    // Parameter: Ustavka 203 : ustavka203 : MB Offset: 202
    uint8_t ustavka203;
    // Parameter: Ustavka 204 : ustavka204 : MB Offset: 203
    uint8_t ustavka204;
    // Parameter: Ustavka 205 : ustavka205 : MB Offset: 204
    uint8_t ustavka205;
    // Parameter: Ustavka 206 : ustavka206 : MB Offset: 205
    uint8_t ustavka206;
    // Parameter: Ustavka 207 : ustavka207 : MB Offset: 206
    uint8_t ustavka207;
    // Parameter: Ustavka 208 : ustavka208 : MB Offset: 207
    uint8_t ustavka208;
    // Parameter: Ustavka 209 : ustavka209 : MB Offset: 208
    uint8_t ustavka209;
    // Parameter: Ustavka 210 : ustavka210 : MB Offset: 209
    uint8_t ustavka210;
    // Parameter: Ustavka 211 : ustavka211 : MB Offset: 210
    uint8_t ustavka211;
    // Parameter: Ustavka 212 : ustavka212 : MB Offset: 211
    uint8_t ustavka212;
    // Parameter: Ustavka 213 : ustavka213 : MB Offset: 212
    uint8_t ustavka213;
    // Parameter: Ustavka 214 : ustavka214 : MB Offset: 213
    uint8_t ustavka214;
    // Parameter: Ustavka 215 : ustavka215 : MB Offset: 214
    uint8_t ustavka215;
    // Parameter: Ustavka 216 : ustavka216 : MB Offset: 215
    uint8_t ustavka216;
    // Parameter: IP Address : ipAddress : MB Offset: 0
    uint32_t ipAddress;
    // Parameter: Mask IP : maskIP : MB Offset: 2
    uint32_t maskIP;
    // Parameter: Broadcast : broadcast : MB Offset: 4
    uint32_t broadcast;
    // Parameter: Port Web Server : portWebServer : MB Offset: 6
    uint16_t portWebServer;
    // Parameter: Reserv Port 1 : reservPort1 : MB Offset: 7
    uint16_t reservPort1;
    // Parameter: Reserv Port 2 : reservPort2 : MB Offset: 8
    uint16_t reservPort2;
    // Parameter: Reserv Port 3 : reservPort3 : MB Offset: 9
    uint16_t reservPort3;
    // Parameter: Modbus TCP IP Address : modbusTcpIpAddress : MB Offset: 10
    uint32_t modbusTcpIpAddress;
    // Parameter: Modbus TCP Mask IP : ModbusTcpMaskIP : MB Offset: 12
    uint32_t ModbusTcpMaskIP;
    // Parameter: Modbus RTU Broadcast : modbusTcpBroadcast : MB Offset: 14
    uint32_t modbusTcpBroadcast;
    // Parameter: Modbus TCP Port : modbusTcpPort : MB Offset: 16
    uint16_t modbusTcpPort;
    // Parameter: Modbus Type : modbusType : MB Offset: 17
    uint16_t modbusType;
    // Parameter: Modbus Slave Address : modbusSlaveAddress : MB Offset: 18
    uint16_t modbusSlaveAddress;
    // Parameter: Modbus RTU Baudrate : modbusRtuBaudrate : MB Offset: 19
    uint32_t modbusRtuBaudrate;
    // Parameter: Modbus RTU Parity : modbusRtuParity : MB Offset: 21
    uint16_t modbusRtuParity;
    // Parameter: Modbus RTU Data Bits : modbusRtuDatabits : MB Offset: 22
    uint16_t modbusRtuDatabits;
    // Parameter: Modbus RTU Stopbit : modbusRtuStopbit : MB Offset: 23
    uint16_t modbusRtuStopbit;
    // Parameter: Display Mode : displayMode : MB Offset: 100
    uint16_t displayMode;
    // Parameter: Display Autoscale : displayAutoscale : MB Offset: 101
    uint16_t displayAutoscale;
    // Parameter: Display Arrows : displayArrows : MB Offset: 102
    uint16_t displayArrows;
    // Parameter: Brightness : brightness : MB Offset: 103
    uint16_t brightness;
    // Parameter: Device Mode : deviceMode : MB Offset: 104
    uint16_t deviceMode;
    // Parameter: Current Date : currentDate : MB Offset: 105
    uint32_t currentDate;
    // Parameter: Current Time : currentTime : MB Offset: 107
    uint32_t currentTime;
    // Parameter: Настройки интерфейсов : var1 : MB Offset: 200
    uint32_t var1;
    // Parameter: Конфигурация уставок : var2 : MB Offset: 1000
    uint32_t var2;
    // Parameter: Конфигурация  матканалов : var3 : MB Offset: 2000
    uint32_t var3;
    // Parameter: Конфигурация модулей (плат) : var4 : MB Offset: 3000
    uint32_t var4;
    // Parameter: Конфигурация аналоговых каналов : var5 : MB Offset: 5000
    uint32_t var5;
    // Parameter: Конфигурация частотных каналов : var6 : MB Offset: 6000
    uint32_t var6;
    // Parameter: Modbus Protocol Version : modbusProtocolVersion : MB Offset: 0
    uint32_t modbusProtocolVersion;
    // Parameter: Hardware Version : hardwareVersion : MB Offset: 100
    uint32_t hardwareVersion;
    // Parameter: Software Version : softwareVersion : MB Offset: 102
    uint32_t softwareVersion;
    // Parameter: Device Type : deviceType : MB Offset: 104
    uint16_t deviceType;
    // Parameter: Device Name : deviceName : MB Offset: 105
    uint8_t deviceName[32];
    // Parameter: Manufacturer : manufacturer : MB Offset: 121
    uint8_t manufacturer[32];
    // Parameter: Web Site : webSite : MB Offset: 137
    uint8_t webSite[32];
    // Parameter: Reserve String : reserveString : MB Offset: 153
    uint8_t reserveString[32];
    // Parameter: Serial Number : serialNumber : MB Offset: 169
    uint8_t serialNumber[32];
    // Parameter: Date Of Manufacture : manufactureDate : MB Offset: 185
    uint32_t manufactureDate;
    // Parameter: Device ID : deviceID : MB Offset: 187
    uint32_t deviceID;
    // Parameter: Device State : deviceState : MB Offset: 200
    uint16_t deviceState;
    // Parameter: Working Time : workingTime : MB Offset: 201
    uint16_t workingTime;
    // Parameter: Modbus Count Errors : modbusCountErrors : MB Offset: 202
    uint16_t modbusCountErrors;
    // Parameter: Modbus Count Goods : modbusCountGoods : MB Offset: 203
    uint16_t modbusCountGoods;
    // Parameter: Count Modules : countModules : MB Offset: 1000
    uint16_t countModules;
    // Parameter: Info Moduls : var7 : MB Offset: 1000
    uint16_t var7;
    // Parameter: Modul 1 : var8 : MB Offset: 1100
    uint16_t var8;
    // Parameter: Modul 2 : var9 : MB Offset: 1200
    uint16_t var9;
    // Parameter: Modul 3 : var10 : MB Offset: 1300
    uint16_t var10;
    // Parameter: Modul 4 : var11 : MB Offset: 1400
    uint16_t var11;
    // Parameter: Modul 5 : var12 : MB Offset: 1500
    uint16_t var12;
    // Parameter: Modul 6 : var13 : MB Offset: 1600
    uint16_t var13;
    // Parameter: Analog channel 1 : analogChan1 : MB Offset: 5000
    float analogChan1;
    // Parameter: Analog channel 2 : analogChan2 : MB Offset: 5002
    float analogChan2;
    // Parameter: Analog channel 3 : analogChan3 : MB Offset: 5004
    float analogChan3;
    // Parameter: Analog channel 4 : analogChan4 : MB Offset: 5006
    float analogChan4;
    // Parameter: Analog channel 5 : analogChan5 : MB Offset: 5008
    float analogChan5;
    // Parameter: Analog channel 6 : analogChan6 : MB Offset: 5010
    float analogChan6;
    // Parameter: Analog channel 7 : analogChan7 : MB Offset: 5012
    float analogChan7;
    // Parameter: Analog channel 8 : analogChan8 : MB Offset: 5014
    float analogChan8;
    // Parameter: Analog channel 9 : analogChan9 : MB Offset: 5016
    float analogChan9;
    // Parameter: Analog channel 10 : analogChan10 : MB Offset: 5018
    float analogChan10;
    // Parameter: Analog channel 11 : analogChan11 : MB Offset: 5020
    float analogChan11;
    // Parameter: Analog channel 12 : analogChan12 : MB Offset: 5022
    float analogChan12;
    // Parameter: Analog channel 13 : analogChan13 : MB Offset: 5024
    float analogChan13;
    // Parameter: Analog channel 14 : analogChan14 : MB Offset: 5026
    float analogChan14;
    // Parameter: Analog channel 15 : analogChan15 : MB Offset: 5028
    float analogChan15;
    // Parameter: Analog channel 16 : analogChan16 : MB Offset: 5030
    float analogChan16;
    // Parameter: Analog channel 17 : analogChan17 : MB Offset: 5032
    float analogChan17;
    // Parameter: Analog channel 18 : analogChan18 : MB Offset: 5034
    float analogChan18;
    // Parameter: Analog channel 19 : analogChan19 : MB Offset: 5036
    float analogChan19;
    // Parameter: Analog channel 20 : analogChan20 : MB Offset: 5038
    float analogChan20;
    // Parameter: Analog channel 21 : analogChan21 : MB Offset: 5040
    float analogChan21;
    // Parameter: Analog channel 22 : analogChan22 : MB Offset: 5042
    float analogChan22;
    // Parameter: Analog channel 23 : analogChan23 : MB Offset: 5044
    float analogChan23;
    // Parameter: Analog channel 24 : analogChan24 : MB Offset: 5046
    float analogChan24;
    // Parameter: Math channel 1 : mathChan1 : MB Offset: 5100
    float mathChan1;
    // Parameter: Math channel 2 : mathChan2 : MB Offset: 5102
    float mathChan2;
    // Parameter: Math channel 3 : mathChan3 : MB Offset: 5104
    float mathChan3;
    // Parameter: Math channel 4 : mathChan4 : MB Offset: 5106
    float mathChan4;
    // Parameter: Math channel 5 : mathChan5 : MB Offset: 5108
    float mathChan5;
    // Parameter: Math channel 6 : mathChan6 : MB Offset: 5110
    float mathChan6;
    // Parameter: Math channel 7 : mathChan7 : MB Offset: 5112
    float mathChan7;
    // Parameter: Math channel 8 : mathChan8 : MB Offset: 5114
    float mathChan8;
    // Parameter: Math channel 9 : mathChan9 : MB Offset: 5116
    float mathChan9;
    // Parameter: Math channel 10 : mathChan10 : MB Offset: 5118
    float mathChan10;
    // Parameter: Math channel 11 : mathChan11 : MB Offset: 5120
    float mathChan11;
    // Parameter: Math channel 12 : mathChan12 : MB Offset: 5122
    float mathChan12;
    // Parameter: Math channel 13 : mathChan13 : MB Offset: 5124
    float mathChan13;
    // Parameter: Math channel 14 : mathChan14 : MB Offset: 5126
    float mathChan14;
    // Parameter: Math channel 15 : mathChan15 : MB Offset: 5128
    float mathChan15;
    // Parameter: Math channel 16 : mathChan16 : MB Offset: 5130
    float mathChan16;
    // Parameter: Math channel 17 : mathChan17 : MB Offset: 5132
    float mathChan17;
    // Parameter: Math channel 18 : mathChan18 : MB Offset: 5134
    float mathChan18;
    // Parameter: Math channel 19 : mathChan19 : MB Offset: 5136
    float mathChan19;
    // Parameter: Math channel 20 : mathChan20 : MB Offset: 5138
    float mathChan20;
    // Parameter: Math channel 21 : mathChan21 : MB Offset: 5140
    float mathChan21;
    // Parameter: Math channel 22 : mathChan22 : MB Offset: 5142
    float mathChan22;
    // Parameter: Math channel 23 : mathChan23 : MB Offset: 5144
    float mathChan23;
    // Parameter: Math channel 24 : mathChan24 : MB Offset: 5146
    float mathChan24;
    // Parameter: Math channel 25 : mathChan25 : MB Offset: 5148
    float mathChan25;
    // Parameter: Math channel 26 : mathChan26 : MB Offset: 5150
    float mathChan26;
    // Parameter: Math channel 27 : mathChan27 : MB Offset: 5152
    float mathChan27;
    // Parameter: Math channel 28 : mathChan28 : MB Offset: 5154
    float mathChan28;
    // Parameter: Math channel 29 : mathChan29 : MB Offset: 5156
    float mathChan29;
    // Parameter: Math channel 30 : mathChan30 : MB Offset: 5158
    float mathChan30;
    // Parameter: Freq channel 1 : freqChan1 : MB Offset: 5200
    float freqChan1;
    // Parameter: Freq channel 2 : freqChan2 : MB Offset: 5202
    float freqChan2;
    // Parameter: Freq channel 3 : freqChan3 : MB Offset: 5204
    float freqChan3;
    // Parameter: Freq channel 4 : freqChan4 : MB Offset: 5206
    float freqChan4;
    // Parameter: Freq channel 5 : freqChan5 : MB Offset: 5208
    float freqChan5;
    // Parameter: Freq channel 6 : freqChan6 : MB Offset: 5210
    float freqChan6;
    // Parameter: Freq channel 7 : freqChan7 : MB Offset: 5212
    float freqChan7;
    // Parameter: Freq channel 8 : freqChan8 : MB Offset: 5214
    float freqChan8;
    // Parameter: Freq channel 9 : freqChan9 : MB Offset: 5216
    float freqChan9;
    // Parameter: Freq channel 10 : freqChan10 : MB Offset: 5218
    float freqChan10;
    // Parameter: Freq channel 11 : freqChan11 : MB Offset: 5220
    float freqChan11;
    // Parameter: Freq channel 12 : freqChan12 : MB Offset: 5222
    float freqChan12;
    // Parameter: Freq channel 13 : freqChan13 : MB Offset: 5224
    float freqChan13;
    // Parameter: Freq channel 14 : freqChan14 : MB Offset: 5226
    float freqChan14;
    // Parameter: Freq channel 15 : freqChan15 : MB Offset: 5228
    float freqChan15;
    // Parameter: Freq channel 16 : freqChan16 : MB Offset: 5230
    float freqChan16;
    // Parameter: Analog Channel Status 1 : analogStatusChan1 : MB Offset: 7000
    uint16_t analogStatusChan1;
    // Parameter: Analog Channel Status 2 : analogStatusChan2 : MB Offset: 7001
    uint16_t analogStatusChan2;
    // Parameter: Analog Channel Status 3 : analogStatusChan3 : MB Offset: 7002
    uint16_t analogStatusChan3;
    // Parameter: Analog Channel Status 4 : analogStatusChan4 : MB Offset: 7003
    uint16_t analogStatusChan4;
    // Parameter: Analog Channel Status 5 : analogStatusChan5 : MB Offset: 7004
    uint16_t analogStatusChan5;
    // Parameter: Analog Channel Status 6 : analogStatusChan6 : MB Offset: 7005
    uint16_t analogStatusChan6;
    // Parameter: Analog Channel Status 7 : analogStatusChan7 : MB Offset: 7006
    uint16_t analogStatusChan7;
    // Parameter: Analog Channel Status 8 : analogStatusChan8 : MB Offset: 7007
    uint16_t analogStatusChan8;
    // Parameter: Analog Channel Status 9 : analogStatusChan9 : MB Offset: 7008
    uint16_t analogStatusChan9;
    // Parameter: Analog Channel Status 10 : analogStatusChan10 : MB Offset: 7009
    uint16_t analogStatusChan10;
    // Parameter: Analog Channel Status 11 : analogStatusChan11 : MB Offset: 7010
    uint16_t analogStatusChan11;
    // Parameter: Analog Channel Status 12 : analogStatusChan12 : MB Offset: 7011
    uint16_t analogStatusChan12;
    // Parameter: Analog Channel Status 13 : analogStatusChan13 : MB Offset: 7012
    uint16_t analogStatusChan13;
    // Parameter: Analog Channel Status 14 : analogStatusChan14 : MB Offset: 7013
    uint16_t analogStatusChan14;
    // Parameter: Analog Channel Status 15 : analogStatusChan15 : MB Offset: 7014
    uint16_t analogStatusChan15;
    // Parameter: Analog Channel Status 16 : analogStatusChan16 : MB Offset: 7015
    uint16_t analogStatusChan16;
    // Parameter: Analog Channel Status 17 : analogStatusChan17 : MB Offset: 7016
    uint16_t analogStatusChan17;
    // Parameter: Analog Channel Status 18 : analogStatusChan18 : MB Offset: 7017
    uint16_t analogStatusChan18;
    // Parameter: Analog Channel Status 19 : analogStatusChan19 : MB Offset: 7018
    uint16_t analogStatusChan19;
    // Parameter: Analog Channel Status 20 : analogStatusChan20 : MB Offset: 7019
    uint16_t analogStatusChan20;
    // Parameter: Analog Channel Status 21 : analogStatusChan21 : MB Offset: 7020
    uint16_t analogStatusChan21;
    // Parameter: Analog Channel Status 22 : analogStatusChan22 : MB Offset: 7021
    uint16_t analogStatusChan22;
    // Parameter: Analog Channel Status 23 : analogStatusChan23 : MB Offset: 7022
    uint16_t analogStatusChan23;
    // Parameter: Analog Channel Status 24 : analogStatusChan24 : MB Offset: 7023
    uint16_t analogStatusChan24;
    // Parameter: Analog Channel Unit 1 : analogUnitChan1 : MB Offset: 7024
    uint8_t analogUnitChan1[8];
    // Parameter: Analog Channel Unit 2 : analogUnitChan2 : MB Offset: 7028
    uint8_t analogUnitChan2[8];
    // Parameter: Analog Channel Unit 3 : analogUnitChan3 : MB Offset: 7032
    uint8_t analogUnitChan3[8];
    // Parameter: Analog Channel Unit 4 : analogUnitChan4 : MB Offset: 7036
    uint8_t analogUnitChan4[8];
    // Parameter: Analog Channel Unit 5 : analogUnitChan5 : MB Offset: 7040
    uint8_t analogUnitChan5[8];
    // Parameter: Analog Channel Unit 6 : analogUnitChan6 : MB Offset: 7044
    uint8_t analogUnitChan6[8];
    // Parameter: Analog Channel Unit 7 : analogUnitChan7 : MB Offset: 7048
    uint8_t analogUnitChan7[8];
    // Parameter: Analog Channel Unit 8 : analogUnitChan8 : MB Offset: 7052
    uint8_t analogUnitChan8[8];
    // Parameter: Analog Channel Unit 9 : analogUnitChan9 : MB Offset: 7056
    uint8_t analogUnitChan9[8];
    // Parameter: Analog Channel Unit 10 : analogUnitChan10 : MB Offset: 7060
    uint8_t analogUnitChan10[8];
    // Parameter: Analog Channel Unit 11 : analogUnitChan11 : MB Offset: 7064
    uint8_t analogUnitChan11[8];
    // Parameter: Analog Channel Unit 12 : analogUnitChan12 : MB Offset: 7068
    uint8_t analogUnitChan12[8];
    // Parameter: Analog Channel Unit 13 : analogUnitChan13 : MB Offset: 7072
    uint8_t analogUnitChan13[8];
    // Parameter: Analog Channel Unit 14 : analogUnitChan14 : MB Offset: 7076
    uint8_t analogUnitChan14[8];
    // Parameter: Analog Channel Unit 15 : analogUnitChan15 : MB Offset: 7080
    uint8_t analogUnitChan15[8];
    // Parameter: Analog Channel Unit 16 : analogUnitChan16 : MB Offset: 7084
    uint8_t analogUnitChan16[8];
    // Parameter: Analog Channel Unit 17 : analogUnitChan17 : MB Offset: 7088
    uint8_t analogUnitChan17[8];
    // Parameter: Analog Channel Unit 18 : analogUnitChan18 : MB Offset: 7092
    uint8_t analogUnitChan18[8];
    // Parameter: Analog Channel Unit 19 : analogUnitChan19 : MB Offset: 7096
    uint8_t analogUnitChan19[8];
    // Parameter: Analog Channel Unit 20 : analogUnitChan20 : MB Offset: 7100
    uint8_t analogUnitChan20[8];
    // Parameter: Analog Channel Unit 21 : analogUnitChan21 : MB Offset: 7104
    uint8_t analogUnitChan21[8];
    // Parameter: Analog Channel Unit 22 : analogUnitChan22 : MB Offset: 7108
    uint8_t analogUnitChan22[8];
    // Parameter: Analog Channel Unit 23 : analogUnitChan23 : MB Offset: 7112
    uint8_t analogUnitChan23[8];
    // Parameter: Analog Channel Unit 24 : analogUnitChan24 : MB Offset: 7116
    uint8_t analogUnitChan24[8];
} tExtDeviceBasicParams;
#pragma pack(pop)
#define PAR_HELPER(fmt, ...) printf(fmt " \ n%; s; ", __VA_ARGS__)
#define PAR(...) PAR_HELPER(__VA_ARGS__, ")
#define PAR_PREF(...) (*(&(g_extModbusDataStorage.##__VA_ARGS__##)))
#define DEVICE_PAR(param) &(g_extModbusDataStorage.##param)
#define DEVICE_PAR_VOID(param) ((void*)&(g_extModbusDataStorage.##param))
#endif // !defined(DEVICE_PARAMS_H)


